* Generated by tools/dsl-l2.mjs from src/l2/maintenance_no_voyage.l2.yaml; do not edit.
* Rule maintenance-ship-no-voyage: A ship in maintenance has no voyage departing after the check date
CLASS zcl_osd_fleet_l2_maint DEFINITION PUBLIC FINAL CREATE PUBLIC.
  PUBLIC SECTION.
    CLASS-METHODS check
      IMPORTING iv_date TYPE d
      RETURNING VALUE(rt_alerts) TYPE string_table.
ENDCLASS.

CLASS zcl_osd_fleet_l2_maint IMPLEMENTATION.
  METHOD check.
    " one query: the tables joined, never a SELECT per row of the first
    TYPES: BEGIN OF ty_join,
             ship_ship_id TYPE zosd_fleet_ship-ship_id,
             voy_voyage_id TYPE zosd_fleet_voy-voyage_id,
             ship_name TYPE zosd_fleet_ship-name,
             voy_dep_date TYPE zosd_fleet_voy-dep_date,
           END OF ty_join.
    DATA lt_join TYPE STANDARD TABLE OF ty_join WITH DEFAULT KEY.
    DATA ls_join TYPE ty_join.
    DATA lv_alert TYPE string.
    SELECT
        ship~ship_id AS ship_ship_id
        voy~voyage_id AS voy_voyage_id
        ship~name AS ship_name
        voy~dep_date AS voy_dep_date
      FROM zosd_fleet_ship AS ship
        INNER JOIN zosd_fleet_voy AS voy
          ON voy~ship_id = ship~ship_id
      INTO CORRESPONDING FIELDS OF TABLE lt_join
      WHERE ship~status = 'M'
        AND voy~dep_date > iv_date
      ORDER BY
        ship~ship_id
        voy~voyage_id.
    LOOP AT lt_join INTO ls_join.
      lv_alert = ls_join-ship_ship_id
        && ` `
        && ls_join-ship_name
        && `: in maintenance, voyage `
        && ls_join-voy_voyage_id
        && ` departs `
        && ls_join-voy_dep_date.
      APPEND lv_alert TO rt_alerts.
    ENDLOOP.
  ENDMETHOD.
ENDCLASS.
