* Generated by tools/dsl-l3.mjs from src/l3/fleet_night.l3.yaml; do not edit.
* Set night: the ports of the set, and the variant each run binds to them.
CLASS zcl_l3_night_ports DEFINITION PUBLIC FINAL CREATE PUBLIC.
  PUBLIC SECTION.
    " the variant bound to a port: a name in iv_bind ("port=variant,port=variant")
    " when the run gives one, else the manifest's binding
    CLASS-METHODS variant
      IMPORTING iv_port TYPE csequence
                iv_bind TYPE string OPTIONAL
      RETURNING VALUE(rv_variant) TYPE string.
    " refuses a binding naming a port or a variant the set does not have, a variant that
    " cannot cross sessions in a run in jobs, a hand-written variant in a replay, and a
    " replay without iv_allow_replay. A replay is a source bound to a generated variant that
    " is not the live table: it swaps table content in the caller LUW, a test and dev seam,
    " never production. This is decided from the manifest's data, below, before any adapter is
    " created: a hand-written class counts as live and not volatile and is never asked.
    CLASS-METHODS check
      IMPORTING iv_bind TYPE string OPTIONAL
                iv_parallel TYPE abap_bool DEFAULT abap_false
                iv_allow_replay TYPE abap_bool DEFAULT abap_false.
    " true when the source port is bound to a generated variant that is not the live table
    CLASS-METHODS swaps
      IMPORTING iv_port TYPE csequence
                iv_bind TYPE string OPTIONAL
      RETURNING VALUE(rv_swaps) TYPE abap_bool.
    CLASS-METHODS get_ships
      IMPORTING iv_variant TYPE csequence
      RETURNING VALUE(ri_port) TYPE REF TO zif_l3_night_ships.
    CLASS-METHODS get_alerts
      IMPORTING iv_variant TYPE csequence
      RETURNING VALUE(ri_port) TYPE REF TO zif_l3_night_alerts.
ENDCLASS.

CLASS zcl_l3_night_ports IMPLEMENTATION.
  METHOD variant.
    DATA lt_parts TYPE string_table.
    DATA lv_part TYPE string.
    DATA lv_name TYPE string.
    DATA lv_value TYPE string.
    CASE iv_port.
      WHEN 'ships'.
        rv_variant = 'table'.
      WHEN 'alerts'.
        rv_variant = 'log'.
      WHEN OTHERS.
        RAISE EXCEPTION TYPE zcx_l3_night_port
          EXPORTING iv_port = iv_port iv_reason = 'no such port in the set'.
    ENDCASE.
    SPLIT iv_bind AT ',' INTO TABLE lt_parts.
    LOOP AT lt_parts INTO lv_part.
      CLEAR: lv_name, lv_value.
      SPLIT lv_part AT '=' INTO lv_name lv_value.
      CONDENSE: lv_name, lv_value.
      IF lv_name = iv_port.
        rv_variant = lv_value.
      ENDIF.
    ENDLOOP.
  ENDMETHOD.

  METHOD swaps.
    DATA lv_variant TYPE string.
    lv_variant = variant( iv_port = iv_port iv_bind = iv_bind ).
    IF iv_port = 'ships'.
    ENDIF.
  ENDMETHOD.

  METHOD check.
    DATA lt_parts TYPE string_table.
    DATA lv_part TYPE string.
    DATA lv_name TYPE string.
    DATA lv_value TYPE string.
    DATA lv_known TYPE abap_bool.
    DATA lv_variant TYPE string.
    DATA lv_volatile_port TYPE string.
    DATA lv_replay_port TYPE string.
    DATA lv_hand_port TYPE string.
    DATA lv_planner_port TYPE string.
    SPLIT iv_bind AT ',' INTO TABLE lt_parts.
    LOOP AT lt_parts INTO lv_part.
      CLEAR: lv_name, lv_value.
      SPLIT lv_part AT '=' INTO lv_name lv_value.
      CONDENSE: lv_name, lv_value.
      IF lv_name IS INITIAL AND lv_value IS INITIAL.
        CONTINUE.
      ENDIF.
      lv_known = abap_false.
      IF lv_name = 'ships'.
        lv_known = abap_true.
      ENDIF.
      IF lv_name = 'alerts'.
        lv_known = abap_true.
      ENDIF.
      IF lv_known = abap_false.
        RAISE EXCEPTION TYPE zcx_l3_night_port
          EXPORTING iv_port = lv_name iv_reason = 'no such port in the set'.
      ENDIF.
    ENDLOOP.
    lv_variant = variant( iv_port = 'ships' iv_bind = iv_bind ).
    lv_known = abap_false.
    IF lv_variant = 'table'.
      lv_known = abap_true.
    ENDIF.
    IF lv_variant = 'worklist'.
      lv_known = abap_true.
      lv_planner_port = 'ships'.
    ENDIF.
    IF lv_known = abap_false.
      RAISE EXCEPTION TYPE zcx_l3_night_port
        EXPORTING iv_port = 'ships' iv_variant = lv_variant
                  iv_reason = 'no such variant for the port'.
    ENDIF.
    lv_variant = variant( iv_port = 'alerts' iv_bind = iv_bind ).
    lv_known = abap_false.
    IF lv_variant = 'log'.
      lv_known = abap_true.
    ENDIF.
    IF lv_known = abap_false.
      RAISE EXCEPTION TYPE zcx_l3_night_port
        EXPORTING iv_port = 'alerts' iv_variant = lv_variant
                  iv_reason = 'no such variant for the port'.
    ENDIF.
    IF lv_planner_port IS NOT INITIAL.
      RAISE EXCEPTION TYPE zcx_l3_night_port
        EXPORTING iv_port = lv_planner_port
                  iv_reason = 'the worklist variant is read by the planner of a stage; a run does not bind it'.
    ENDIF.
    IF iv_parallel = abap_true AND lv_volatile_port IS NOT INITIAL.
      RAISE EXCEPTION TYPE zcx_l3_night_port
        EXPORTING iv_port = lv_volatile_port
                  iv_reason = 'the variant keeps its rows in this session, a job cannot use it'.
    ENDIF.
    IF iv_parallel = abap_true AND lv_replay_port IS NOT INITIAL.
      RAISE EXCEPTION TYPE zcx_l3_night_port
        EXPORTING iv_port = lv_replay_port
                  iv_reason = 'the variant replaces the table content, a run in jobs cannot'.
    ENDIF.
    IF lv_replay_port IS NOT INITIAL AND lv_hand_port IS NOT INITIAL.
      RAISE EXCEPTION TYPE zcx_l3_night_port
        EXPORTING iv_port = lv_hand_port
                  iv_reason = 'a replay binds generated variants only: a hand-written class can commit, and no scan sees what it calls'.
    ENDIF.
    IF lv_replay_port IS NOT INITIAL AND iv_allow_replay = abap_false.
      RAISE EXCEPTION TYPE zcx_l3_night_port
        EXPORTING iv_port = lv_replay_port
                  iv_reason = 'a replay swaps table content in the caller LUW; for a test or a dev run only, never production: pass iv_allow_replay'.
    ENDIF.
  ENDMETHOD.

  METHOD get_ships.
    CASE iv_variant.
      WHEN 'table'.
        CREATE OBJECT ri_port TYPE zcl_l3_night_ships_table.
      WHEN 'worklist'.
        CREATE OBJECT ri_port TYPE zcl_l3_night_ships_worklist.
      WHEN OTHERS.
        RAISE EXCEPTION TYPE zcx_l3_night_port
          EXPORTING iv_port = 'ships' iv_variant = iv_variant
                    iv_reason = 'no such variant for the port'.
    ENDCASE.
  ENDMETHOD.

  METHOD get_alerts.
    CASE iv_variant.
      WHEN 'log'.
        CREATE OBJECT ri_port TYPE zcl_l3_night_alerts_log.
      WHEN OTHERS.
        RAISE EXCEPTION TYPE zcx_l3_night_port
          EXPORTING iv_port = 'alerts' iv_variant = iv_variant
                    iv_reason = 'no such variant for the port'.
    ENDCASE.
  ENDMETHOD.
ENDCLASS.
