* Generated by tools/dsl-l3.mjs from src/l3/fleet_watch.l3.yaml; do not edit.
* Generic application-data settings of set watch.
CLASS zcl_l3_watch_conf DEFINITION PUBLIC FINAL CREATE PUBLIC.
  PUBLIC SECTION.
    TYPES: BEGIN OF ty_values,
             budget_glass TYPE i,
           END OF ty_values.
    TYPES tt_conf TYPE STANDARD TABLE OF zosd_l3_conf WITH DEFAULT KEY.
    TYPES: BEGIN OF ty_state,
             vals TYPE ty_values,
             rows TYPE tt_conf,
             warnings TYPE string_table,
             fallback TYPE string_table,
           END OF ty_state.
    CLASS-METHODS specs RETURNING VALUE(rt_specs) TYPE tt_conf.
    CLASS-METHODS settings_seed.
    " the compiled DSL defaults: what every reader falls back to, never a zero
    CLASS-METHODS defaults RETURNING VALUE(rs_vals) TYPE ty_values.
    " iv_write = abap_false (a dry run, a job): read only, nothing seeded or logged
    CLASS-METHODS load
      IMPORTING iv_write TYPE abap_bool DEFAULT abap_true
      RETURNING VALUE(rs_state) TYPE ty_state.
    CLASS-METHODS snapshot IMPORTING iv_run TYPE csequence is_state TYPE ty_state.
    " is_vals with the values that belong to run iv_run (the fuse, the pile
    " sizes, the parameters) taken from its snapshot ZOSD_L3_RUN_CONF; a value
    " the snapshot lacks or holds invalid is the compiled default
    CLASS-METHODS scope
      IMPORTING iv_run TYPE csequence is_vals TYPE ty_values
      RETURNING VALUE(rs_vals) TYPE ty_values.
    " is_vals with each value outside its type or bounds (a selection field
    " that did not arrive reads as zero) replaced by the compiled default
    CLASS-METHODS sane
      IMPORTING is_vals TYPE ty_values
      RETURNING VALUE(rs_vals) TYPE ty_values.
    CLASS-METHODS set_setting
      IMPORTING iv_param TYPE csequence iv_value TYPE csequence iv_note TYPE csequence
      RETURNING VALUE(rv_ok) TYPE abap_bool.
    CLASS-METHODS reset_setting
      IMPORTING iv_param TYPE csequence
      RETURNING VALUE(rv_ok) TYPE abap_bool.
    " every setting of the set back to its DSL default
    CLASS-METHODS reset_all
      RETURNING VALUE(rv_ok) TYPE abap_bool.
  PRIVATE SECTION.
    CLASS-METHODS valid
      IMPORTING iv_param TYPE csequence iv_value TYPE csequence
      RETURNING VALUE(rv_ok) TYPE abap_bool.
    CLASS-METHODS audit
      IMPORTING is_old TYPE zosd_l3_conf is_new TYPE zosd_l3_conf iv_note TYPE csequence.
    CLASS-METHODS authorised RETURNING VALUE(rv_ok) TYPE abap_bool.
ENDCLASS.

CLASS zcl_l3_watch_conf IMPLEMENTATION.
  METHOD specs.
    DATA ls_spec TYPE zosd_l3_conf.
    ls_spec-set_name = 'watch'.
    CLEAR ls_spec.
    ls_spec-set_name = 'watch'.
    ls_spec-param_name = 'budget.glass'.
    ls_spec-dsl_value = '1'.
    APPEND ls_spec TO rt_specs.
  ENDMETHOD.

  METHOD defaults.
    rs_vals-budget_glass = '1'.
  ENDMETHOD.

  METHOD sane.
    DATA ls_def TYPE ty_values.
    DATA lv_text TYPE c LENGTH 40.
    DATA lv_number TYPE p LENGTH 16 DECIMALS 0.
    ls_def = defaults( ).
    rs_vals = is_vals.
    lv_number = is_vals-budget_glass.
    lv_text = abs( lv_number ).
    CONDENSE lv_text.
    IF lv_number < 0.
      CONCATENATE '-' lv_text INTO lv_text.
    ENDIF.
    IF valid( iv_param = 'budget.glass' iv_value = lv_text ) = abap_false.
      rs_vals-budget_glass = ls_def-budget_glass.
    ENDIF.
  ENDMETHOD.

  METHOD scope.
    DATA lt_rows TYPE STANDARD TABLE OF zosd_l3_run_conf WITH DEFAULT KEY.
    DATA ls_row TYPE zosd_l3_run_conf.
    DATA ls_def TYPE ty_values.
    DATA lv_value TYPE c LENGTH 40.
    rs_vals = is_vals.
    ls_def = defaults( ).
    SELECT * FROM zosd_l3_run_conf INTO TABLE lt_rows
      WHERE run_id = iv_run AND set_name = 'watch'.
    rs_vals-budget_glass = ls_def-budget_glass.
    READ TABLE lt_rows INTO ls_row WITH KEY param_name = 'budget.glass'.
    IF sy-subrc = 0.
      lv_value = ls_row-param_val.
      IF valid( iv_param = 'budget.glass' iv_value = lv_value ) = abap_true.
        rs_vals-budget_glass = lv_value.
      ENDIF.
    ENDIF.
  ENDMETHOD.

  METHOD valid.
    DATA lv_number TYPE p LENGTH 16 DECIMALS 0.
    DATA lv_text TYPE string.
    DATA lv_length TYPE i.
    DATA lv_offset TYPE i.
    DATA lv_unit TYPE c LENGTH 1.
    lv_text = iv_value.
    rv_ok = abap_false.
    CASE iv_param.
      WHEN 'budget.glass'.
        IF lv_text IS INITIAL OR strlen( lv_text ) > 20.
          RETURN.
        ENDIF.
        FIND REGEX '^-?[0-9]+$' IN lv_text.
        IF sy-subrc <> 0.
          RETURN.
        ENDIF.
        lv_number = lv_text.
        IF lv_number < 1 OR lv_number > 2147483647.
          RETURN.
        ENDIF.
        rv_ok = abap_true.
    ENDCASE.
  ENDMETHOD.

  METHOD audit.
    DATA ls_log TYPE zosd_l3_conf_log.
    DATA lv_stamp TYPE timestampl.
    TRY.
        ls_log-change_id = cl_system_uuid=>create_uuid_c32_static( ).
      CATCH cx_uuid_error.
        GET TIME STAMP FIELD lv_stamp.
        ls_log-change_id = lv_stamp.
    ENDTRY.
    ls_log-set_name = is_new-set_name.
    ls_log-param_name = is_new-param_name.
    ls_log-old_value = is_old-param_val.
    ls_log-new_value = is_new-param_val.
    ls_log-old_origin = is_old-origin.
    ls_log-new_origin = is_new-origin.
    ls_log-changed_by = sy-uname.
    GET TIME STAMP FIELD ls_log-changed_at.
    ls_log-note_text = iv_note.
    INSERT zosd_l3_conf_log FROM ls_log.
  ENDMETHOD.

  METHOD authorised.
    " A productive system checks its own assigned role or authority here.
    " No SAP authorisation object is assumed by this generated runtime.
    rv_ok = abap_true.
  ENDMETHOD.

  METHOD settings_seed.
    DATA ls_state TYPE ty_state.
    ls_state = load( ).
  ENDMETHOD.

  METHOD load.
    DATA lt_specs TYPE tt_conf.
    DATA lt_found TYPE tt_conf.
    DATA lv_logged TYPE i.
    DATA ls_spec TYPE zosd_l3_conf.
    DATA ls_row TYPE zosd_l3_conf.
    DATA ls_old TYPE zosd_l3_conf.
    DATA lv_effective TYPE c LENGTH 40.
    DATA lv_warning TYPE string.
    lt_specs = specs( ).
    " One settings SELECT per pass; the same rows seed and supply values.
    SELECT * FROM zosd_l3_conf INTO TABLE lt_found WHERE set_name = 'watch'.
    LOOP AT lt_specs INTO ls_spec.
      READ TABLE lt_found INTO ls_row WITH KEY param_name = ls_spec-param_name.
      IF sy-subrc <> 0.
        ls_row = ls_spec.
        ls_row-param_val = ls_spec-dsl_value.
        ls_row-origin = 'DSL'.
        ls_row-changed_by = sy-uname.
        GET TIME STAMP FIELD ls_row-changed_at.
        IF iv_write = abap_true.
          INSERT zosd_l3_conf FROM ls_row.
          IF sy-subrc = 0.
            CLEAR ls_old.
            audit( is_old = ls_old is_new = ls_row iv_note = 'DSL seed' ).
          ELSE.
            " seeded by a first run beside this one: its row, and its log entry
            SELECT SINGLE * FROM zosd_l3_conf INTO ls_row
              WHERE set_name = 'watch' AND param_name = ls_spec-param_name.
          ENDIF.
        ENDIF.
      ELSEIF ls_row-dsl_value <> ls_spec-dsl_value.
        ls_old = ls_row.
        ls_row-dsl_value = ls_spec-dsl_value.
        IF ls_row-origin = 'DSL'.
          ls_row-param_val = ls_spec-dsl_value.
          ls_row-changed_by = sy-uname.
          GET TIME STAMP FIELD ls_row-changed_at.
        ENDIF.
        IF iv_write = abap_true.
          UPDATE zosd_l3_conf FROM ls_row.
          audit( is_old = ls_old is_new = ls_row iv_note = 'DSL default changed' ).
        ENDIF.
      ENDIF.
      lv_effective = ls_row-param_val.
      IF valid( iv_param = ls_row-param_name iv_value = lv_effective ) = abap_false.
        lv_effective = ls_spec-dsl_value.
        CONCATENATE ls_row-param_name 'invalid; DSL default used' INTO lv_warning SEPARATED BY space.
        APPEND lv_warning TO rs_state-warnings.
        APPEND ls_row-param_name TO rs_state-fallback.
        " logged once per stored value, not once per pass
        IF iv_write = abap_true.
          SELECT COUNT(*) FROM zosd_l3_conf_log INTO lv_logged
            WHERE set_name = ls_row-set_name AND param_name = ls_row-param_name
              AND new_value = ls_row-param_val AND note_text = 'invalid; DSL default used'.
          IF lv_logged = 0.
            audit( is_old = ls_row is_new = ls_row iv_note = 'invalid; DSL default used' ).
          ENDIF.
        ENDIF.
      ENDIF.
      ls_row-param_val = lv_effective.
      APPEND ls_row TO rs_state-rows.
      CASE ls_row-param_name.
        WHEN 'budget.glass'.
          rs_state-vals-budget_glass = lv_effective.
      ENDCASE.
    ENDLOOP.
  ENDMETHOD.

  METHOD snapshot.
    DATA ls_conf TYPE zosd_l3_conf.
    DATA ls_run TYPE zosd_l3_run_conf.
    LOOP AT is_state-rows INTO ls_conf.
      CLEAR ls_run.
      ls_run-run_id = iv_run.
      ls_run-set_name = 'watch'.
      ls_run-param_name = ls_conf-param_name.
      ls_run-param_val = ls_conf-param_val.
      ls_run-origin = ls_conf-origin.
      ls_run-dsl_value = ls_conf-dsl_value.
      ls_run-changed_by = ls_conf-changed_by.
      ls_run-changed_at = ls_conf-changed_at.
      " the stored value was invalid and the run used the compiled default:
      " neither the operator's value nor the operator's name is the run's
      READ TABLE is_state-fallback TRANSPORTING NO FIELDS WITH KEY table_line = ls_conf-param_name.
      IF sy-subrc = 0.
        ls_run-origin = 'FALLBACK'.
        CLEAR: ls_run-changed_by, ls_run-changed_at.
      ENDIF.
      INSERT zosd_l3_run_conf FROM ls_run.
    ENDLOOP.
  ENDMETHOD.

  METHOD set_setting.
    DATA lt_specs TYPE tt_conf.
    DATA ls_spec TYPE zosd_l3_conf.
    DATA ls_row TYPE zosd_l3_conf.
    DATA ls_old TYPE zosd_l3_conf.
    DATA ls_current TYPE ty_state.
    DATA lv_warn TYPE i.
    DATA lv_narrow TYPE i.
    rv_ok = abap_false.
    IF authorised( ) = abap_false OR valid( iv_param = iv_param iv_value = iv_value ) = abap_false.
      RETURN.
    ENDIF.
    lt_specs = specs( ).
    READ TABLE lt_specs INTO ls_spec WITH KEY param_name = iv_param.
    IF sy-subrc <> 0.
      RETURN.
    ENDIF.
    settings_seed( ).
    IF iv_param = 'budget.warn' OR iv_param = 'budget.narrow_at'.
      " fixed lock order for concurrent edits of the two thresholds
      SELECT SINGLE FOR UPDATE * FROM zosd_l3_conf INTO ls_old
        WHERE set_name = 'watch' AND param_name = 'budget.warn'.
      SELECT SINGLE FOR UPDATE * FROM zosd_l3_conf INTO ls_old
        WHERE set_name = 'watch' AND param_name = 'budget.narrow_at'.
      ls_current = load( iv_write = abap_false ).
      lv_warn = 7000.
      lv_narrow = 8000.
      IF iv_param = 'budget.warn'.
        lv_warn = iv_value.
      ELSE.
        lv_narrow = iv_value.
      ENDIF.
      IF lv_warn > lv_narrow OR lv_narrow > 10000.
        RETURN.
      ENDIF.
    ENDIF.
    SELECT SINGLE * FROM zosd_l3_conf INTO ls_row
      WHERE set_name = 'watch' AND param_name = iv_param.
    IF sy-subrc <> 0.
      RETURN.
    ENDIF.
    ls_old = ls_row.
    ls_row-param_val = iv_value.
    ls_row-origin = 'USER'.
    ls_row-note_text = iv_note.
    ls_row-changed_by = sy-uname.
    GET TIME STAMP FIELD ls_row-changed_at.
    UPDATE zosd_l3_conf FROM ls_row.
    audit( is_old = ls_old is_new = ls_row iv_note = iv_note ).
    rv_ok = abap_true.
  ENDMETHOD.

  METHOD reset_setting.
    DATA lt_specs TYPE tt_conf.
    DATA ls_spec TYPE zosd_l3_conf.
    DATA ls_row TYPE zosd_l3_conf.
    DATA ls_old TYPE zosd_l3_conf.
    rv_ok = abap_false.
    IF authorised( ) = abap_false.
      RETURN.
    ENDIF.
    lt_specs = specs( ).
    READ TABLE lt_specs INTO ls_spec WITH KEY param_name = iv_param.
    IF sy-subrc <> 0.
      RETURN.
    ENDIF.
    settings_seed( ).
    SELECT SINGLE * FROM zosd_l3_conf INTO ls_row
      WHERE set_name = 'watch' AND param_name = iv_param.
    IF sy-subrc <> 0.
      RETURN.
    ENDIF.
    rv_ok = abap_true.
    " already the DSL default: nothing changes and nothing is logged
    IF ls_row-origin = 'DSL' AND ls_row-param_val = ls_spec-dsl_value.
      RETURN.
    ENDIF.
    ls_old = ls_row.
    ls_row-param_val = ls_spec-dsl_value.
    ls_row-origin = 'DSL'.
    ls_row-note_text = 'reset to DSL default'.
    ls_row-changed_by = sy-uname.
    GET TIME STAMP FIELD ls_row-changed_at.
    UPDATE zosd_l3_conf FROM ls_row.
    audit( is_old = ls_old is_new = ls_row iv_note = 'reset to DSL default' ).
  ENDMETHOD.

  METHOD reset_all.
    DATA lt_specs TYPE tt_conf.
    DATA ls_spec TYPE zosd_l3_conf.
    rv_ok = abap_true.
    lt_specs = specs( ).
    LOOP AT lt_specs INTO ls_spec.
      IF reset_setting( ls_spec-param_name ) = abap_false.
        rv_ok = abap_false.
      ENDIF.
    ENDLOOP.
  ENDMETHOD.
ENDCLASS.
