* Generated by tools/dsl-l3.mjs from src/l3/fleet_watch.l3.yaml; do not edit.
* Port alerts of set watch, variant capture: keeps the rows in memory for a test to read.
CLASS zcl_l3_watch_alerts_capture DEFINITION PUBLIC FINAL CREATE PUBLIC.
  PUBLIC SECTION.
    INTERFACES zif_l3_watch_alerts.
    CLASS-DATA gt_rows TYPE zif_l3_watch_alerts=>tt_rows.
    CLASS-METHODS rows
      RETURNING VALUE(rt_rows) TYPE zif_l3_watch_alerts=>tt_rows.
    CLASS-METHODS reset.
ENDCLASS.

CLASS zcl_l3_watch_alerts_capture IMPLEMENTATION.
  METHOD rows.
    rt_rows = gt_rows.
  ENDMETHOD.

  METHOD reset.
    CLEAR gt_rows.
  ENDMETHOD.

  METHOD zif_l3_watch_alerts~put.
    APPEND LINES OF it_rows TO gt_rows.
    rv_count = lines( it_rows ).
  ENDMETHOD.
ENDCLASS.
