* Generated by tools/dsl-l3.mjs from src/l3/fleet_night.l3.yaml; do not edit.
* Set night: The fleet at night, busy ships first, then the deep checks
CLASS zcl_osd_fleet_night DEFINITION PUBLIC FINAL CREATE PUBLIC.
  PUBLIC SECTION.
    TYPES: BEGIN OF ty_rule,
             rule TYPE zosd_l3_alert-rule_name,
             model_hash TYPE zosd_l3_alert-model_hash,
             jobname TYPE tbtcjob-jobname,
             jobcount TYPE tbtcjob-jobcount,
             status TYPE c LENGTH 12,
             alerts TYPE i,
             failed TYPE i,
             piles TYPE i,
             piles_done TYPE i,
             stage_no TYPE i,
             filter TYPE abap_bool,
             keys TYPE i,
           END OF ty_rule.
    TYPES tt_rule TYPE STANDARD TABLE OF ty_rule WITH DEFAULT KEY.
    TYPES tt_pile TYPE STANDARD TABLE OF zosd_l3_pile WITH DEFAULT KEY.
    " a stage of the run: WAITING, OPEN, SUBMITTED, DONE, PARTIAL or NOT-RUN
    TYPES: BEGIN OF ty_stage,
             stage_no TYPE i,
             stage TYPE zosd_l3_stage-stage_name,
             status TYPE c LENGTH 12,
             piles TYPE i,
             piles_done TYPE i,
           END OF ty_stage.
    TYPES tt_stage TYPE STANDARD TABLE OF ty_stage WITH DEFAULT KEY.
    TYPES tt_range_1 TYPE RANGE OF zosd_fleet_ship-ship_id.
    TYPES tt_range_2 TYPE RANGE OF zosd_fleet_ship-ship_id.
    TYPES: BEGIN OF ty_result,
             set_name TYPE zosd_l3_alert-set_name,
             run_id TYPE zosd_l3_alert-run_id,
             check_date TYPE d,
             mode TYPE c LENGTH 1,
             alerts TYPE i,
             rules TYPE tt_rule,
             bind TYPE string,
             status TYPE c LENGTH 12,
             stages TYPE tt_stage,
           END OF ty_result.
    CONSTANTS c_set TYPE zosd_l3_alert-set_name VALUE 'night'.
    CONSTANTS c_sequential TYPE c LENGTH 1 VALUE 'S'.
    CONSTANTS c_parallel TYPE c LENGTH 1 VALUE 'P'.
    CONSTANTS c_rule_1 TYPE zosd_l3_alert-rule_name VALUE 'busy-ship'.
    CONSTANTS c_hash_1 TYPE zosd_l3_alert-model_hash VALUE 'sha256:669c875572d3a250f2020e3e44b62750ff83291fa6303e191b690aa45f6c6154'.
    CONSTANTS c_rule_2 TYPE zosd_l3_alert-rule_name VALUE 'low-steam-voyage'.
    CONSTANTS c_hash_2 TYPE zosd_l3_alert-model_hash VALUE 'sha256:429e1ae70d5ff582572094dc7506171521411b61fc4f2d50ebb17fb4740dc6cf'.
    CONSTANTS c_rule_3 TYPE zosd_l3_alert-rule_name VALUE 'maintenance-voyage'.
    CONSTANTS c_hash_3 TYPE zosd_l3_alert-model_hash VALUE 'sha256:ffaa917988d887b4a6e6615d9aec57e77cc5e601830d268bd4b2fad5ac7b915b'.
    " stage 1, a filter: its rules fill worklist busy, piles of 2 keys of zosd_fleet_ship-ship_id
    CONSTANTS c_stage_1 TYPE zosd_l3_stage-stage_name VALUE 'candidates'.
    " stage 2, piles of 2 keys of zosd_fleet_ship-ship_id in worklist busy
    CONSTANTS c_stage_2 TYPE zosd_l3_stage-stage_name VALUE 'checks'.
    CONSTANTS c_stages TYPE i VALUE 2.
    " the driver job of the schedule: every 1d, system time
    CONSTANTS c_driver TYPE tbtcjob-jobname VALUE 'L3_NIGHT_D'.
    " iv_bind: the variant of each port for this run, "port=variant,port=variant";
    " a port it does not name keeps the manifest's binding. A source that is not
    " live replaces table content in the caller's LUW: a test and dev seam, never
    " production, and refused unless iv_allow_replay says so.
    CLASS-METHODS run
      IMPORTING iv_date TYPE d
                iv_mode TYPE c DEFAULT 'S'
                iv_bind TYPE string OPTIONAL
                iv_allow_replay TYPE abap_bool DEFAULT abap_false
      RETURNING VALUE(rs_result) TYPE ty_result.
    " the plan of one stage, made when the stage opens: a row per rule and pile
    CLASS-METHODS plan
      IMPORTING iv_run TYPE csequence
                iv_date TYPE d
                iv_stage TYPE i
                iv_bind TYPE string OPTIONAL
      RETURNING VALUE(rt_piles) TYPE tt_pile.
    " the gate, called by a pile's job once its pile is DONE and committed:
    " when every pile of iv_stage is DONE the next stage opens, once
    CLASS-METHODS advance
      IMPORTING iv_run TYPE csequence
                iv_date TYPE d
                iv_stage TYPE i
                iv_bind TYPE string OPTIONAL
      RETURNING VALUE(rv_opened) TYPE abap_bool.
    CLASS-METHODS run_rule
      IMPORTING iv_rule TYPE csequence
                iv_date TYPE d
                iv_run TYPE csequence
                iv_pile TYPE i
                iv_bind TYPE string OPTIONAL
      RETURNING VALUE(rs_rule) TYPE ty_rule.
    CLASS-METHODS collect
      IMPORTING is_result TYPE ty_result
      RETURNING VALUE(rs_result) TYPE ty_result.
    CLASS-METHODS rules
      RETURNING VALUE(rt_rules) TYPE tt_rule.
    " the set as a periodic background job: ZL3_<SET> with p_mode = 'D' (one
    " run in jobs for the current date) every 1d, first at the time
    " schedule: names, in system time (sy-datum, sy-uzeit), never the user's
    " a second call while an instance waits answers that instance's count and
    " opens no second chain
    CLASS-METHODS schedule
      RETURNING VALUE(rv_jobcount) TYPE tbtcjob-jobcount.
    " the count of the driver's instance waiting for its start (status S) for
    " this user, or initial when the set is not scheduled
    CLASS-METHODS scheduled
      RETURNING VALUE(rv_jobcount) TYPE tbtcjob-jobcount.
    " deletes the waiting instance of the driver, which ends the chain
    CLASS-METHODS unschedule
      RETURNING VALUE(rv_deleted) TYPE i.
  PRIVATE SECTION.
    CLASS-METHODS write
      IMPORTING iv_date TYPE d
                iv_run TYPE csequence
                iv_pile TYPE i
                iv_class TYPE csequence
                iv_file TYPE csequence
                iv_line TYPE i
                it_alerts TYPE string_table
                iv_bind TYPE string OPTIONAL
      CHANGING cs_rule TYPE ty_rule.
    " one run of the set per check date at a time: ZOSD_L3_RUN
    CLASS-METHODS lock
      IMPORTING iv_run TYPE csequence
                iv_date TYPE d
      RETURNING VALUE(rv_locked) TYPE abap_bool.
    CLASS-METHODS release
      IMPORTING iv_run TYPE csequence
                iv_date TYPE d.
    CLASS-METHODS finalise
      IMPORTING iv_rule TYPE csequence
                iv_hash TYPE csequence
                iv_date TYPE d
                iv_run TYPE csequence
                iv_bind TYPE string.
    CLASS-METHODS stages
      RETURNING VALUE(rt_stages) TYPE tt_stage.
    " a filter rule's keys into the run's worklist (ZOSD_L3_WORK)
    CLASS-METHODS fill
      IMPORTING iv_run TYPE csequence
                iv_date TYPE d
                iv_worklist TYPE csequence
                it_keys TYPE string_table
      CHANGING cs_rule TYPE ty_rule.
    " the range of a pile of stage 1, from its plan row
    CLASS-METHODS range_1
      IMPORTING is_pile TYPE zosd_l3_pile
      RETURNING VALUE(rt_range) TYPE tt_range_1.
    " the range of a pile of stage 2, from its plan row and worklist busy
    CLASS-METHODS range_2
      IMPORTING is_pile TYPE zosd_l3_pile
      RETURNING VALUE(rt_range) TYPE tt_range_2.
    " puts the rows of zosd_fleet_ship back after a replay: the rows kept before it
    CLASS-METHODS restore_1
      IMPORTING it_keep TYPE zif_l3_night_ships=>tt_rows.
    CLASS-METHODS submit
      IMPORTING iv_date TYPE d
                iv_run TYPE csequence
                iv_bind TYPE string OPTIONAL
                iv_jobname TYPE csequence
      CHANGING cs_pile TYPE zosd_l3_pile.
ENDCLASS.

CLASS zcl_osd_fleet_night IMPLEMENTATION.
  METHOD run.
    " stage by stage: a stage opens through its gate row in ZOSD_L3_STAGE
    " (WAITING to OPEN), is planned then (a later stage reads the worklist an
    " earlier one filled) and runs. Mode S runs every stage in this step and
    " stops at a stage that is not DONE; mode P submits the piles of the first
    " stage that has any, and the job that ends a stage opens the next one
    DATA lt_rules TYPE tt_rule.
    DATA ls_rule TYPE ty_rule.
    DATA lt_piles TYPE tt_pile.
    DATA ls_pile TYPE zosd_l3_pile.
    DATA ls_part TYPE ty_rule.
    DATA lt_stages TYPE tt_stage.
    DATA ls_stage TYPE ty_stage.
    DATA ls_gate TYPE zosd_l3_stage.
    DATA lv_stop TYPE abap_bool.
    DATA lv_open TYPE abap_bool.
    DATA lv_stamp TYPE timestampl.
    DATA lv_parallel TYPE abap_bool.
    DATA lx_error TYPE REF TO cx_root.
    DATA li_src_1 TYPE REF TO zif_l3_night_ships.
    DATA lv_swap_1 TYPE abap_bool.
    DATA lt_keep_1 TYPE zif_l3_night_ships=>tt_rows.
    DATA lt_scope_1 TYPE zif_l3_night_ships=>tt_rows.
    FIELD-SYMBOLS <ls_row_1> TYPE zosd_fleet_ship.
    IF iv_mode = c_parallel.
      lv_parallel = abap_true.
    ENDIF.
    zcl_l3_night_ports=>check( iv_bind = iv_bind
                          iv_parallel = lv_parallel
                          iv_allow_replay = iv_allow_replay ).
    rs_result-set_name = c_set.
    rs_result-mode = iv_mode.
    rs_result-bind = iv_bind.
    rs_result-check_date = iv_date.
    TRY.
        rs_result-run_id = cl_system_uuid=>create_uuid_c32_static( ).
      CATCH cx_uuid_error.
        GET TIME STAMP FIELD lv_stamp.
        rs_result-run_id = lv_stamp.
    ENDTRY.
    " one run of the set per check date at a time: a run that finds the lock
    " held by another answers BUSY and plans nothing
    IF lock( iv_run = rs_result-run_id iv_date = rs_result-check_date ) = abap_false.
      rs_result-status = 'BUSY'.
      RETURN.
    ENDIF.
    lt_rules = rules( ).
    " a source that is not live replaces table content for this run, and the
    " table is put back whatever happens: after the loop, or when an exception
    " leaves this method (CATCH and RAISE, which does what CLEANUP would; the
    " transpiler drops CLEANUP, ANORMALIES.md). Nothing in here commits.
    TRY.
        " zosd_fleet_ship: the table's own rows are kept, the source's rows stand
        " in their place, and the rules read them as they read the table
        IF zcl_l3_night_ports=>swaps( iv_port = 'ships' iv_bind = iv_bind ) = abap_true.
          li_src_1 = zcl_l3_night_ports=>get_ships( zcl_l3_night_ports=>variant( iv_port = 'ships' iv_bind = iv_bind ) ).
          SELECT * FROM zosd_fleet_ship INTO TABLE lt_keep_1.
          lt_scope_1 = li_src_1->read( ).
          LOOP AT lt_scope_1 ASSIGNING <ls_row_1>.
            <ls_row_1>-mandt = sy-mandt.
          ENDLOOP.
          lv_swap_1 = abap_true.
          DELETE FROM zosd_fleet_ship.
          INSERT zosd_fleet_ship FROM TABLE lt_scope_1.
        ENDIF.
        " the gate rows: every stage WAITING; a stage opens once, WAITING to OPEN
        lt_stages = stages( ).
        ls_gate-set_name = c_set.
        ls_gate-run_id = rs_result-run_id.
        ls_gate-check_date = rs_result-check_date.
        ls_gate-status = 'WAITING'.
        LOOP AT lt_stages INTO ls_stage.
          ls_gate-stage_no = ls_stage-stage_no.
          ls_gate-stage_name = ls_stage-stage.
          INSERT zosd_l3_stage FROM ls_gate.
        ENDLOOP.
        LOOP AT lt_stages INTO ls_stage.
          IF lv_stop = abap_true.
            " after a stage that did not end DONE, or after the stage whose
            " jobs were just submitted: not opened by this step
            ls_stage-status = 'WAITING'.
            LOOP AT lt_rules INTO ls_rule WHERE stage_no = ls_stage-stage_no.
              ls_rule-status = 'WAITING'.
              APPEND ls_rule TO rs_result-rules.
            ENDLOOP.
            APPEND ls_stage TO rs_result-stages.
            CONTINUE.
          ENDIF.
          GET TIME STAMP FIELD lv_stamp.
          UPDATE zosd_l3_stage SET status = 'OPEN' opened = lv_stamp
            WHERE run_id = rs_result-run_id
              AND stage_no = ls_stage-stage_no
              AND status = 'WAITING'.
          lt_piles = plan( iv_run = rs_result-run_id
                           iv_date = rs_result-check_date
                           iv_stage = ls_stage-stage_no
                           iv_bind = iv_bind ).
          INSERT zosd_l3_pile FROM TABLE lt_piles.
          ls_stage-piles = lines( lt_piles ).
          IF iv_mode = c_parallel AND lt_piles IS NOT INITIAL.
            " mode P: this stage's piles as jobs; the job that ends the stage opens the next
            LOOP AT lt_rules INTO ls_rule WHERE stage_no = ls_stage-stage_no.
              ls_rule-status = 'SUBMITTED'.
              LOOP AT lt_piles INTO ls_pile WHERE rule_name = ls_rule-rule.
                ls_rule-piles = ls_rule-piles + 1.
                submit( EXPORTING iv_date = rs_result-check_date
                                  iv_run = rs_result-run_id
                                  iv_bind = iv_bind
                                  iv_jobname = ls_rule-jobname
                        CHANGING cs_pile = ls_pile ).
                IF ls_pile-status = 'FAILED'.
                  ls_rule-status = 'PARTIAL'.
                ENDIF.
              ENDLOOP.
              APPEND ls_rule TO rs_result-rules.
            ENDLOOP.
            ls_stage-status = 'SUBMITTED'.
            lv_stop = abap_true.
            lv_open = abap_true.
          ELSE.
            " mode S, or a stage without a pile: every pile in this step. A
            " rule is DONE when every pile is, and only then finalised
            LOOP AT lt_rules INTO ls_rule WHERE stage_no = ls_stage-stage_no.
              LOOP AT lt_piles INTO ls_pile WHERE rule_name = ls_rule-rule.
                ls_rule-piles = ls_rule-piles + 1.
                ls_part = run_rule( iv_rule = ls_rule-rule
                                    iv_date = rs_result-check_date
                                    iv_run = rs_result-run_id
                                    iv_pile = ls_pile-pile_no
                                    iv_bind = iv_bind ).
                ls_rule-alerts = ls_rule-alerts + ls_part-alerts.
                ls_rule-keys = ls_rule-keys + ls_part-keys.
                ls_rule-failed = ls_rule-failed + ls_part-failed.
                ls_rule-piles_done = ls_rule-piles_done + ls_part-piles_done.
              ENDLOOP.
              IF ls_rule-piles_done = ls_rule-piles.
                ls_rule-status = 'DONE'.
                finalise( iv_rule = ls_rule-rule
                          iv_hash = ls_rule-model_hash
                          iv_date = rs_result-check_date
                          iv_run = rs_result-run_id
                          iv_bind = iv_bind ).
              ELSE.
                ls_rule-status = 'PARTIAL'.
              ENDIF.
              ls_stage-piles_done = ls_stage-piles_done + ls_rule-piles_done.
              rs_result-alerts = rs_result-alerts + ls_rule-alerts.
              APPEND ls_rule TO rs_result-rules.
            ENDLOOP.
            IF ls_stage-piles_done = ls_stage-piles.
              ls_stage-status = 'DONE'.
            ELSE.
              ls_stage-status = 'PARTIAL'.
              lv_stop = abap_true.
            ENDIF.
            GET TIME STAMP FIELD lv_stamp.
            UPDATE zosd_l3_stage SET status = ls_stage-status ended = lv_stamp
              WHERE run_id = rs_result-run_id
                AND stage_no = ls_stage-stage_no.
          ENDIF.
          APPEND ls_stage TO rs_result-stages.
        ENDLOOP.
        " mode P holds the lock while a stage's jobs are open; else the run is final
        IF lv_open = abap_true.
          rs_result-status = 'SUBMITTED'.
        ELSE.
          rs_result-status = 'DONE'.
          LOOP AT rs_result-stages INTO ls_stage WHERE status <> 'DONE'.
            rs_result-status = 'PARTIAL'.
          ENDLOOP.
          release( iv_run = rs_result-run_id iv_date = rs_result-check_date ).
        ENDIF.
      CATCH cx_root INTO lx_error.
        release( iv_run = rs_result-run_id iv_date = rs_result-check_date ).
        IF lv_swap_1 = abap_true.
          restore_1( lt_keep_1 ).
        ENDIF.
        RAISE EXCEPTION lx_error.
    ENDTRY.
    IF lv_swap_1 = abap_true.
      restore_1( lt_keep_1 ).
    ENDIF.
  ENDMETHOD.

  METHOD plan.
    " the plan of one stage, made when the stage opens. A piled stage reads
    " its keys through its source port (over a worklist: the port's worklist
    " variant, the keys an earlier stage of this run filled), sorted and
    " without repeats, cut into consecutive chunks of its size; a rule that
    " is not piled is one pile, number 0, over every row. No key, no pile
    DATA lt_cut TYPE tt_pile.
    DATA ls_pile TYPE zosd_l3_pile.
    DATA lv_count TYPE i.
    DATA li_source_1 TYPE REF TO zif_l3_night_ships.
    DATA lt_keys_1 TYPE zif_l3_night_ships=>tt_rows.
    DATA ls_key_1 LIKE LINE OF lt_keys_1.
    DATA li_source_2 TYPE REF TO zif_l3_night_ships.
    DATA lt_keys_2 TYPE zif_l3_night_ships=>tt_rows.
    DATA ls_key_2 LIKE LINE OF lt_keys_2.
    ls_pile-set_name = c_set.
    ls_pile-run_id = iv_run.
    ls_pile-check_date = iv_date.
    ls_pile-stage_no = iv_stage.
    ls_pile-status = 'PLANNED'.
    CASE iv_stage.
      WHEN 1.
        li_source_1 = zcl_l3_night_ports=>get_ships( zcl_l3_night_ports=>variant( iv_port = 'ships' iv_bind = iv_bind ) ).
        lt_keys_1 = li_source_1->read( ).
        SORT lt_keys_1 BY ship_id.
        DELETE ADJACENT DUPLICATES FROM lt_keys_1 COMPARING ship_id.
        LOOP AT lt_keys_1 INTO ls_key_1.
          IF lv_count = 0.
            ls_pile-pile_no = ls_pile-pile_no + 1.
            ls_pile-range_low = ls_key_1-ship_id.
          ENDIF.
          ls_pile-range_high = ls_key_1-ship_id.
          lv_count = lv_count + 1.
          IF lv_count = 2.
            APPEND ls_pile TO lt_cut.
            lv_count = 0.
          ENDIF.
        ENDLOOP.
        IF lv_count > 0.
          APPEND ls_pile TO lt_cut.
        ENDIF.
        " busy-ship: piled, its range: is the key
        LOOP AT lt_cut INTO ls_pile.
          ls_pile-rule_name = c_rule_1.
          ls_pile-model_hash = c_hash_1.
          APPEND ls_pile TO rt_piles.
        ENDLOOP.
      WHEN 2.
        " the keys worklist busy holds for this run
        zcl_l3_night_ships_worklist=>use( iv_run = iv_run iv_worklist = 'busy' ).
        li_source_2 = zcl_l3_night_ports=>get_ships( 'worklist' ).
        lt_keys_2 = li_source_2->read( ).
        SORT lt_keys_2 BY ship_id.
        DELETE ADJACENT DUPLICATES FROM lt_keys_2 COMPARING ship_id.
        LOOP AT lt_keys_2 INTO ls_key_2.
          IF lv_count = 0.
            ls_pile-pile_no = ls_pile-pile_no + 1.
            ls_pile-range_low = ls_key_2-ship_id.
          ENDIF.
          ls_pile-range_high = ls_key_2-ship_id.
          lv_count = lv_count + 1.
          IF lv_count = 2.
            APPEND ls_pile TO lt_cut.
            lv_count = 0.
          ENDIF.
        ENDLOOP.
        IF lv_count > 0.
          APPEND ls_pile TO lt_cut.
        ENDIF.
        " low-steam-voyage: piled, its range: is the key
        LOOP AT lt_cut INTO ls_pile.
          ls_pile-rule_name = c_rule_2.
          ls_pile-model_hash = c_hash_2.
          APPEND ls_pile TO rt_piles.
        ENDLOOP.
        " maintenance-voyage: piled, its range: is the key
        LOOP AT lt_cut INTO ls_pile.
          ls_pile-rule_name = c_rule_3.
          ls_pile-model_hash = c_hash_3.
          APPEND ls_pile TO rt_piles.
        ENDLOOP.
    ENDCASE.
  ENDMETHOD.

  METHOD stages.
    DATA ls_stage TYPE ty_stage.
    ls_stage-stage_no = 1.
    ls_stage-stage = c_stage_1.
    APPEND ls_stage TO rt_stages.
    ls_stage-stage_no = 2.
    ls_stage-stage = c_stage_2.
    APPEND ls_stage TO rt_stages.
  ENDMETHOD.

  METHOD advance.
    " every pile of stage iv_stage DONE: the stage is DONE and the next one
    " opens. The gate is one UPDATE from WAITING to OPEN, so of two jobs that
    " end the stage at once only the one that gets sy-dbcnt = 1 plans and
    " submits it. A stage without a pile is DONE at once and the one after it
    " opens; past the last stage the run is complete: every rule finalised
    " (all are DONE) and the lock released
    DATA lt_piles TYPE tt_pile.
    DATA ls_pile TYPE zosd_l3_pile.
    DATA lt_rules TYPE tt_rule.
    DATA ls_rule TYPE ty_rule.
    DATA lv_stage TYPE i.
    DATA lv_stamp TYPE timestampl.
    SELECT COUNT(*) FROM zosd_l3_pile
      WHERE set_name = c_set
        AND run_id = iv_run
        AND stage_no = iv_stage
        AND status <> 'DONE'.
    IF sy-dbcnt > 0.
      RETURN.
    ENDIF.
    GET TIME STAMP FIELD lv_stamp.
    UPDATE zosd_l3_stage SET status = 'DONE' ended = lv_stamp
      WHERE run_id = iv_run
        AND stage_no = iv_stage
        AND status = 'OPEN'.
    lt_rules = rules( ).
    lv_stage = iv_stage + 1.
    WHILE lv_stage <= c_stages.
      UPDATE zosd_l3_stage SET status = 'OPEN' opened = lv_stamp
        WHERE run_id = iv_run
          AND stage_no = lv_stage
          AND status = 'WAITING'.
      IF sy-dbcnt <> 1.
        RETURN.
      ENDIF.
      rv_opened = abap_true.
      lt_piles = plan( iv_run = iv_run
                       iv_date = iv_date
                       iv_stage = lv_stage
                       iv_bind = iv_bind ).
      INSERT zosd_l3_pile FROM TABLE lt_piles.
      IF lt_piles IS NOT INITIAL.
        LOOP AT lt_piles INTO ls_pile.
          READ TABLE lt_rules INTO ls_rule WITH KEY rule = ls_pile-rule_name.
          submit( EXPORTING iv_date = iv_date
                            iv_run = iv_run
                            iv_bind = iv_bind
                            iv_jobname = ls_rule-jobname
                  CHANGING cs_pile = ls_pile ).
        ENDLOOP.
        RETURN.
      ENDIF.
      UPDATE zosd_l3_stage SET status = 'DONE' ended = lv_stamp
        WHERE run_id = iv_run
          AND stage_no = lv_stage.
      lv_stage = lv_stage + 1.
    ENDWHILE.
    LOOP AT lt_rules INTO ls_rule.
      finalise( iv_rule = ls_rule-rule
                iv_hash = ls_rule-model_hash
                iv_date = iv_date
                iv_run = iv_run
                iv_bind = iv_bind ).
    ENDLOOP.
    release( iv_run = iv_run iv_date = iv_date ).
  ENDMETHOD.

  METHOD fill.
    " a filter rule's keys go into the run's worklist, MODIFY on the full
    " key, so a retried pile writes the same rows; the alert log gets none
    DATA ls_work TYPE zosd_l3_work.
    DATA lv_key TYPE string.
    ls_work-set_name = c_set.
    ls_work-run_id = iv_run.
    ls_work-worklist = iv_worklist.
    ls_work-check_date = iv_date.
    LOOP AT it_keys INTO lv_key.
      ls_work-key_value = lv_key.
      MODIFY zosd_l3_work FROM ls_work.
      IF sy-subrc <> 0.
        cs_rule-failed = cs_rule-failed + 1.
      ENDIF.
    ENDLOOP.
    cs_rule-keys = lines( it_keys ).
    IF cs_rule-failed = 0.
      cs_rule-status = 'DONE'.
    ELSE.
      cs_rule-status = 'WRITE-FAILED'.
    ENDIF.
  ENDMETHOD.

  METHOD range_1.
    DATA ls_range LIKE LINE OF rt_range.
    IF is_pile-pile_no = 0.
      RETURN.
    ENDIF.
    ls_range-sign = 'I'.
    ls_range-low = is_pile-range_low.
    IF is_pile-range_high = is_pile-range_low.
      ls_range-option = 'EQ'.
    ELSE.
      ls_range-option = 'BT'.
      ls_range-high = is_pile-range_high.
    ENDIF.
    APPEND ls_range TO rt_range.
  ENDMETHOD.

  METHOD range_2.
    " a pile over a worklist is the worklist's keys between its bounds, each
    " I EQ: a key between them that the filter did not select stays out
    DATA lt_values TYPE STANDARD TABLE OF zosd_l3_work-key_value WITH DEFAULT KEY.
    DATA lv_value TYPE zosd_l3_work-key_value.
    DATA ls_range LIKE LINE OF rt_range.
    IF is_pile-pile_no = 0.
      RETURN.
    ENDIF.
    ls_range-sign = 'I'.
    ls_range-option = 'EQ'.
    SELECT key_value FROM zosd_l3_work INTO TABLE lt_values
      WHERE run_id = is_pile-run_id
        AND worklist = 'busy'
        AND key_value BETWEEN is_pile-range_low AND is_pile-range_high.
    LOOP AT lt_values INTO lv_value.
      ls_range-low = lv_value.
      APPEND ls_range TO rt_range.
    ENDLOOP.
    IF rt_range IS NOT INITIAL.
      RETURN.
    ENDIF.
    " no worklist row left: the bounds the plan recorded, each a key it held
    ls_range-low = is_pile-range_low.
    APPEND ls_range TO rt_range.
    ls_range-low = is_pile-range_high.
    APPEND ls_range TO rt_range.
  ENDMETHOD.

  METHOD restore_1.
    DELETE FROM zosd_fleet_ship.
    INSERT zosd_fleet_ship FROM TABLE it_keep.
  ENDMETHOD.

  METHOD rules.
    DATA ls_rule TYPE ty_rule.
    ls_rule-rule = c_rule_1.
    ls_rule-model_hash = c_hash_1.
    ls_rule-jobname = 'L3_NIGHT_101'.
    ls_rule-stage_no = 1.
    ls_rule-filter = abap_true.
    APPEND ls_rule TO rt_rules.
    ls_rule-rule = c_rule_2.
    ls_rule-model_hash = c_hash_2.
    ls_rule-jobname = 'L3_NIGHT_202'.
    ls_rule-stage_no = 2.
    ls_rule-filter = abap_false.
    APPEND ls_rule TO rt_rules.
    ls_rule-rule = c_rule_3.
    ls_rule-model_hash = c_hash_3.
    ls_rule-jobname = 'L3_NIGHT_203'.
    ls_rule-stage_no = 2.
    ls_rule-filter = abap_false.
    APPEND ls_rule TO rt_rules.
  ENDMETHOD.

  METHOD run_rule.
    " a pile of one rule: its plan row RUNNING now, DONE or FAILED at the end;
    " a filter rule's keys go to its worklist, a check rule's alerts to the log
    DATA lt_alerts TYPE string_table.
    DATA lt_found TYPE string_table.
    DATA ls_pile TYPE zosd_l3_pile.
    DATA lt_range_1 TYPE tt_range_1.
    DATA lt_range_2 TYPE tt_range_2.
    DATA lt_keys_1 TYPE zcl_osd_fleet_l3_busy=>tt_range.
    DATA ls_key_1 LIKE LINE OF lt_keys_1.
    rs_rule-rule = iv_rule.
    SELECT SINGLE * FROM zosd_l3_pile INTO ls_pile
      WHERE set_name = c_set
        AND run_id = iv_run
        AND rule_name = iv_rule
        AND pile_no = iv_pile.
    IF sy-subrc <> 0.
      rs_rule-status = 'NO-PILE'.
      RETURN.
    ENDIF.
    rs_rule-piles = 1.
    ls_pile-status = 'RUNNING'.
    GET TIME STAMP FIELD ls_pile-started.
    UPDATE zosd_l3_pile FROM ls_pile.
    CASE iv_rule.
      WHEN c_rule_1.
        rs_rule-model_hash = c_hash_1.
        rs_rule-jobname = 'L3_NIGHT_101'.
        rs_rule-stage_no = 1.
        lt_range_1 = range_1( ls_pile ).
        rs_rule-filter = abap_true.
        lt_keys_1 = zcl_osd_fleet_l3_busy=>keys( iv_date = iv_date it_range = lt_range_1 ).
        LOOP AT lt_keys_1 INTO ls_key_1.
          APPEND ls_key_1-low TO lt_found.
        ENDLOOP.
        fill( EXPORTING iv_run = iv_run
                        iv_date = iv_date
                        iv_worklist = 'busy'
                        it_keys = lt_found
              CHANGING cs_rule = rs_rule ).
      WHEN c_rule_2.
        rs_rule-model_hash = c_hash_2.
        rs_rule-jobname = 'L3_NIGHT_202'.
        rs_rule-stage_no = 2.
        lt_range_2 = range_2( ls_pile ).
        lt_alerts = zcl_osd_fleet_l3_steam=>check( iv_date = iv_date it_range = lt_range_2 ).
        write( EXPORTING iv_date = iv_date
                         iv_run = iv_run
                         iv_pile = iv_pile
                         iv_class = 'zcl_osd_fleet_l3_steam'
                         iv_file = 'src/l3/low_steam_voyage.l2.yaml'
                         iv_line = 12
                         it_alerts = lt_alerts
                         iv_bind = iv_bind
               CHANGING cs_rule = rs_rule ).
      WHEN c_rule_3.
        rs_rule-model_hash = c_hash_3.
        rs_rule-jobname = 'L3_NIGHT_203'.
        rs_rule-stage_no = 2.
        lt_range_2 = range_2( ls_pile ).
        lt_alerts = zcl_osd_fleet_l3_maint=>check( iv_date = iv_date it_range = lt_range_2 ).
        write( EXPORTING iv_date = iv_date
                         iv_run = iv_run
                         iv_pile = iv_pile
                         iv_class = 'zcl_osd_fleet_l3_maint'
                         iv_file = 'src/l3/maintenance_voyage.l2.yaml'
                         iv_line = 12
                         it_alerts = lt_alerts
                         iv_bind = iv_bind
               CHANGING cs_rule = rs_rule ).
      WHEN OTHERS.
        rs_rule-status = 'UNKNOWN'.
    ENDCASE.
    " a filter pile's ALERTS column holds the keys it selected
    ls_pile-alerts = rs_rule-alerts + rs_rule-keys.
    GET TIME STAMP FIELD ls_pile-ended.
    IF rs_rule-status = 'DONE'.
      ls_pile-status = 'DONE'.
      rs_rule-piles_done = 1.
    ELSE.
      ls_pile-status = 'FAILED'.
    ENDIF.
    UPDATE zosd_l3_pile FROM ls_pile.
  ENDMETHOD.

  METHOD write.
    " the rows of one rule version and date go through the alert sink the run
    " is bound to (alerts); the log variant is idempotent per (set,
    " rule, model hash, check date), see its class
    DATA ls_row TYPE zosd_l3_alert.
    DATA lt_rows TYPE zif_l3_night_alerts=>tt_rows.
    DATA ls_group TYPE zif_l3_night_alerts=>ty_group.
    DATA li_sink TYPE REF TO zif_l3_night_alerts.
    DATA lv_alert TYPE string.
    DATA lv_count TYPE i.
    ls_row-set_name = c_set.
    ls_row-rule_name = cs_rule-rule.
    ls_row-model_hash = cs_rule-model_hash.
    ls_row-check_date = iv_date.
    ls_row-pile_no = iv_pile.
    ls_row-run_id = iv_run.
    ls_row-rule_class = iv_class.
    ls_row-rule_file = iv_file.
    ls_row-rule_line = iv_line.
    GET TIME STAMP FIELD ls_row-run_ts.
    LOOP AT it_alerts INTO lv_alert.
      ls_row-alert_seq = sy-tabix.
      ls_row-alert_text = lv_alert.
      APPEND ls_row TO lt_rows.
    ENDLOOP.
    ls_group-set_name = c_set.
    ls_group-rule_name = cs_rule-rule.
    ls_group-model_hash = cs_rule-model_hash.
    ls_group-check_date = iv_date.
    ls_group-pile_no = iv_pile.
    li_sink = zcl_l3_night_ports=>get_alerts( zcl_l3_night_ports=>variant( iv_port = 'alerts' iv_bind = iv_bind ) ).
    lv_count = li_sink->put( it_rows = lt_rows
                             is_group = ls_group ).
    cs_rule-alerts = lines( lt_rows ).
    cs_rule-failed = cs_rule-alerts - lv_count.
    IF cs_rule-failed = 0.
      cs_rule-status = 'DONE'.
    ELSE.
      cs_rule-status = 'WRITE-FAILED'.
    ENDIF.
  ENDMETHOD.

  METHOD lock.
    " INSERT takes a set and date never run, UPDATE one whose last run
    " released it; each is one statement, so of two runs at once one wins.
    " The row stays after the release and names the latest run
    DATA ls_run TYPE zosd_l3_run.
    ls_run-set_name = c_set.
    ls_run-check_date = iv_date.
    ls_run-run_id = iv_run.
    ls_run-status = 'HELD'.
    GET TIME STAMP FIELD ls_run-started.
    INSERT zosd_l3_run FROM ls_run.
    IF sy-subrc = 0.
      rv_locked = abap_true.
      RETURN.
    ENDIF.
    UPDATE zosd_l3_run SET run_id = ls_run-run_id status = ls_run-status started = ls_run-started
      WHERE set_name = c_set
        AND check_date = iv_date
        AND status = 'RELEASED'.
    IF sy-dbcnt = 1.
      rv_locked = abap_true.
    ENDIF.
  ENDMETHOD.

  METHOD release.
    UPDATE zosd_l3_run SET status = 'RELEASED'
      WHERE set_name = c_set
        AND check_date = iv_date
        AND run_id = iv_run.
  ENDMETHOD.

  METHOD finalise.
    " every pile of the rule is DONE in this run: the rows of the same set,
    " rule, model hash and date that an older run wrote, under piles cut
    " elsewhere, go. The alert key has no run, so only the latest run of the
    " set and date may finalise: a late collect( ) of an older run would
    " delete the slots a newer run rewrote. Only the log keeps older runs; a
    " run bound to another variant of alerts leaves the log as it is
    DATA lv_latest TYPE zosd_l3_run-run_id.
    SELECT SINGLE run_id FROM zosd_l3_run INTO lv_latest
      WHERE set_name = c_set
        AND check_date = iv_date.
    IF lv_latest <> iv_run.
      RETURN.
    ENDIF.
    IF zcl_l3_night_ports=>variant( iv_port = 'alerts' iv_bind = iv_bind ) <> 'log'.
      RETURN.
    ENDIF.
    DELETE FROM zosd_l3_alert
      WHERE set_name = c_set
        AND rule_name = iv_rule
        AND model_hash = iv_hash
        AND check_date = iv_date
        AND run_id <> iv_run.
  ENDMETHOD.

  METHOD submit.
    " one job per pile: JOB_OPEN, SUBMIT ... VIA JOB, JOB_CLOSE started at
    " once, named L3_<SET>_<nn>_<pppp> (the last four digits of the pile);
    " the job finds its range in the plan row by set, run, rule and pile
    DATA lv_jobname TYPE tbtcjob-jobname.
    DATA lv_jobcount TYPE tbtcjob-jobcount.
    DATA lv_released TYPE btch0000-char1.
    DATA lv_pile TYPE n LENGTH 4.
    lv_pile = cs_pile-pile_no.
    CONCATENATE iv_jobname '_' lv_pile INTO lv_jobname.
    CALL FUNCTION 'JOB_OPEN'
      EXPORTING
        jobname = lv_jobname
      IMPORTING
        jobcount = lv_jobcount
      EXCEPTIONS
        OTHERS = 1.
    IF sy-subrc <> 0.
      cs_pile-status = 'FAILED'.
      UPDATE zosd_l3_pile FROM cs_pile.
      RETURN.
    ENDIF.
    cs_pile-job_name = lv_jobname.
    cs_pile-job_count = lv_jobcount.
    UPDATE zosd_l3_pile FROM cs_pile.
    SUBMIT zosd_fleet_night
      WITH p_rule = cs_pile-rule_name
      WITH p_date = iv_date
      WITH p_run = iv_run
      WITH p_pile = cs_pile-pile_no
      WITH p_bind = iv_bind
      VIA JOB lv_jobname NUMBER lv_jobcount
      AND RETURN.
    CALL FUNCTION 'JOB_CLOSE'
      EXPORTING
        jobname = lv_jobname
        jobcount = lv_jobcount
        strtimmed = 'X'
      IMPORTING
        job_was_released = lv_released
      EXCEPTIONS
        OTHERS = 1.
    IF sy-subrc <> 0 OR lv_released <> 'X'.
      cs_pile-status = 'FAILED'.
      UPDATE zosd_l3_pile FROM cs_pile.
    ENDIF.
  ENDMETHOD.

  METHOD schedule.
    " JOB_OPEN, the driver as the job's step, JOB_CLOSE at a date and time with
    " a period (prddays): the job facade and a system both read SDLSTRTDT and
    " SDLSTRTTM as system time, which sy-datum and sy-uzeit are
    DATA lv_jobname TYPE tbtcjob-jobname.
    DATA lv_date TYPE d.
    DATA lv_time TYPE t.
    DATA lv_period TYPE tbtcjob-prddays.
    DATA lv_released TYPE btch0000-char1.
    " already scheduled: the waiting instance is the chain, a second would run the set twice
    rv_jobcount = scheduled( ).
    IF rv_jobcount IS NOT INITIAL.
      RETURN.
    ENDIF.
    lv_period = 1.
    lv_jobname = c_driver.
    GET TIME.
    lv_date = sy-datum.
    lv_time = '020000'.
    " a first start that has passed today is tomorrow's
    IF lv_time <= sy-uzeit.
      lv_date = lv_date + 1.
    ENDIF.
    CALL FUNCTION 'JOB_OPEN'
      EXPORTING
        jobname = lv_jobname
      IMPORTING
        jobcount = rv_jobcount
      EXCEPTIONS
        OTHERS = 1.
    IF sy-subrc <> 0.
      CLEAR rv_jobcount.
      RETURN.
    ENDIF.
    SUBMIT zosd_fleet_night
      WITH p_mode = 'D'
      VIA JOB lv_jobname NUMBER rv_jobcount
      AND RETURN.
    CALL FUNCTION 'JOB_CLOSE'
      EXPORTING
        jobname = lv_jobname
        jobcount = rv_jobcount
        sdlstrtdt = lv_date
        sdlstrttm = lv_time
        prddays = lv_period
      IMPORTING
        job_was_released = lv_released
      EXCEPTIONS
        OTHERS = 1.
    IF sy-subrc <> 0 OR lv_released <> 'X'.
      " not released: the opened job goes, it would only wait unreleased
      CALL FUNCTION 'BP_JOB_DELETE'
        EXPORTING
          jobname = lv_jobname
          jobcount = rv_jobcount
        EXCEPTIONS
          OTHERS = 1.
      CLEAR rv_jobcount.
    ENDIF.
  ENDMETHOD.

  METHOD scheduled.
    DATA ls_select TYPE btcselect.
    DATA lt_jobs TYPE STANDARD TABLE OF tbtcjob WITH DEFAULT KEY.
    DATA ls_job TYPE tbtcjob.
    ls_select-jobname = c_driver.
    ls_select-username = sy-uname.
    ls_select-schedul = 'X'.
    CALL FUNCTION 'BP_JOB_SELECT'
      EXPORTING
        jobselect_dialog = 'N'
        jobsel_param_in = ls_select
      TABLES
        jobselect_joblist = lt_jobs
      EXCEPTIONS
        OTHERS = 1.
    IF sy-subrc <> 0.
      RETURN.
    ENDIF.
    LOOP AT lt_jobs INTO ls_job WHERE status = 'S'.
      rv_jobcount = ls_job-jobcount.
      RETURN.
    ENDLOOP.
  ENDMETHOD.

  METHOD unschedule.
    " the driver's instance that waits for its start (status S) is the chain:
    " a periodic job's successor is made when an instance starts, so deleting
    " the waiting one ends it (measured on a system, docs/job-standard-fms.md)
    DATA ls_select TYPE btcselect.
    DATA lt_jobs TYPE STANDARD TABLE OF tbtcjob WITH DEFAULT KEY.
    DATA ls_job TYPE tbtcjob.
    ls_select-jobname = c_driver.
    ls_select-username = sy-uname.
    ls_select-schedul = 'X'.
    CALL FUNCTION 'BP_JOB_SELECT'
      EXPORTING
        jobselect_dialog = 'N'
        jobsel_param_in = ls_select
      TABLES
        jobselect_joblist = lt_jobs
      EXCEPTIONS
        OTHERS = 1.
    IF sy-subrc <> 0.
      RETURN.
    ENDIF.
    LOOP AT lt_jobs INTO ls_job WHERE status = 'S'.
      CALL FUNCTION 'BP_JOB_DELETE'
        EXPORTING
          jobname = ls_job-jobname
          jobcount = ls_job-jobcount
        EXCEPTIONS
          OTHERS = 1.
      IF sy-subrc = 0.
        rv_deleted = rv_deleted + 1.
      ENDIF.
    ENDLOOP.
  ENDMETHOD.

  METHOD collect.
    " the run's plan rows and gate rows. An open pile's job is read by
    " SHOW_JOBSTATE: a job that ended without its pile DONE, or no job at
    " all, makes the pile FAILED. A stage whose piles are all DONE while its
    " gate is still OPEN (its last job ended before it could advance) is
    " advanced here. A stage with a FAILED pile is PARTIAL once every pile of
    " it is final, and the stages after it are NOT-RUN: their gate closes, so
    " no late job opens one. The run is final when every stage is DONE, or a
    " stage is PARTIAL and the rest NOT-RUN; only then is the lock released
    DATA lt_piles TYPE tt_pile.
    DATA ls_pile TYPE zosd_l3_pile.
    DATA lt_gates TYPE STANDARD TABLE OF zosd_l3_stage WITH DEFAULT KEY.
    DATA ls_gate TYPE zosd_l3_stage.
    DATA ls_stage TYPE ty_stage.
    DATA lv_state TYPE c LENGTH 12.
    DATA lv_open TYPE c LENGTH 12.
    DATA lv_lost TYPE abap_bool.
    DATA lv_final TYPE abap_bool VALUE abap_true.
    DATA lv_closed TYPE abap_bool.
    DATA lv_stamp TYPE timestampl.
    DATA lv_job_name TYPE zosd_l3_pile-job_name.
    DATA lv_job_count TYPE zosd_l3_pile-job_count.
    DATA ls_rule TYPE ty_rule.
    DATA lv_aborted TYPE btch0000-char1.
    DATA lv_finished TYPE btch0000-char1.
    DATA lv_running TYPE btch0000-char1.
    DATA lv_ready TYPE btch0000-char1.
    DATA lv_scheduled TYPE btch0000-char1.
    DATA lv_preliminary TYPE btch0000-char1.
    rs_result = is_result.
    CLEAR: rs_result-rules, rs_result-alerts.
    CLEAR rs_result-stages.
    SELECT * FROM zosd_l3_pile INTO TABLE lt_piles
      WHERE set_name = c_set
        AND run_id = is_result-run_id
      ORDER BY PRIMARY KEY.
    LOOP AT lt_piles INTO ls_pile WHERE status <> 'DONE' AND status <> 'FAILED'.
      lv_state = 'NO-JOB'.
      IF ls_pile-job_count IS NOT INITIAL.
        CLEAR: lv_aborted, lv_finished, lv_running, lv_ready, lv_scheduled, lv_preliminary.
        CALL FUNCTION 'SHOW_JOBSTATE'
          EXPORTING
            jobname = ls_pile-job_name
            jobcount = ls_pile-job_count
          IMPORTING
            aborted = lv_aborted
            finished = lv_finished
            preliminary = lv_preliminary
            ready = lv_ready
            running = lv_running
            scheduled = lv_scheduled
          EXCEPTIONS
            OTHERS = 1.
        IF sy-subrc <> 0.
          lv_state = 'NO-JOB'.
        ELSEIF lv_finished = 'X'.
          lv_state = 'FINISHED'.
        ELSEIF lv_aborted = 'X'.
          lv_state = 'ABORTED'.
        ELSE.
          lv_state = 'OPEN'.
        ENDIF.
      ENDIF.
      IF lv_state <> 'OPEN'.
        " the job is over: the row as it left it, DONE or not. Only for the
        " job whose state was read above: a pile given another job meanwhile
        " (its planner's, or a later submit of it) is not this job's to fail
        lv_job_name = ls_pile-job_name.
        lv_job_count = ls_pile-job_count.
        SELECT SINGLE * FROM zosd_l3_pile INTO ls_pile
          WHERE set_name = c_set
            AND run_id = ls_pile-run_id
            AND rule_name = ls_pile-rule_name
            AND pile_no = ls_pile-pile_no.
        IF ls_pile-status <> 'DONE'
            AND ls_pile-job_name = lv_job_name AND ls_pile-job_count = lv_job_count.
          " one UPDATE on the row as read, and on the job that was checked
          GET TIME STAMP FIELD ls_pile-ended.
          UPDATE zosd_l3_pile SET status = 'FAILED' ended = ls_pile-ended
            WHERE run_id = ls_pile-run_id
              AND rule_name = ls_pile-rule_name
              AND pile_no = ls_pile-pile_no
              AND status = ls_pile-status
              AND job_name = lv_job_name
              AND job_count = lv_job_count.
        ENDIF.
      ENDIF.
    ENDLOOP.
    " a gate the last job of its stage did not get to
    SELECT * FROM zosd_l3_stage INTO TABLE lt_gates
      WHERE run_id = is_result-run_id
      ORDER BY PRIMARY KEY.
    LOOP AT lt_gates INTO ls_gate WHERE status = 'OPEN'.
      advance( iv_run = is_result-run_id
               iv_date = is_result-check_date
               iv_stage = ls_gate-stage_no
               iv_bind = is_result-bind ).
    ENDLOOP.
    SELECT * FROM zosd_l3_pile INTO TABLE lt_piles
      WHERE set_name = c_set
        AND run_id = is_result-run_id
      ORDER BY PRIMARY KEY.
    SELECT * FROM zosd_l3_stage INTO TABLE lt_gates
      WHERE run_id = is_result-run_id
      ORDER BY PRIMARY KEY.
    LOOP AT lt_gates INTO ls_gate.
      CLEAR ls_stage.
      ls_stage-stage_no = ls_gate-stage_no.
      ls_stage-stage = ls_gate-stage_name.
      CLEAR lv_lost.
      lv_open = ls_gate-status.
      LOOP AT lt_piles INTO ls_pile WHERE stage_no = ls_gate-stage_no.
        ls_stage-piles = ls_stage-piles + 1.
        IF ls_pile-status = 'DONE'.
          ls_stage-piles_done = ls_stage-piles_done + 1.
        ELSEIF ls_pile-status = 'FAILED'.
          lv_lost = abap_true.
        ELSE.
          lv_open = 'RUNNING'.
        ENDIF.
      ENDLOOP.
      GET TIME STAMP FIELD lv_stamp.
      IF ls_gate-status = 'WAITING' AND lv_closed = abap_true.
        " after a PARTIAL stage: never opened, and now never opens
        UPDATE zosd_l3_stage SET status = 'NOT-RUN' ended = lv_stamp
          WHERE run_id = is_result-run_id
            AND stage_no = ls_gate-stage_no
            AND status = 'WAITING'.
        ls_stage-status = 'NOT-RUN'.
      ELSEIF ls_gate-status = 'WAITING'.
        ls_stage-status = 'WAITING'.
        lv_final = abap_false.
      ELSEIF ls_gate-status = 'NOT-RUN'.
        ls_stage-status = 'NOT-RUN'.
        lv_closed = abap_true.
      ELSEIF lv_open = 'RUNNING'.
        ls_stage-status = 'RUNNING'.
        lv_final = abap_false.
      ELSEIF lv_lost = abap_true.
        UPDATE zosd_l3_stage SET status = 'PARTIAL' ended = lv_stamp
          WHERE run_id = is_result-run_id
            AND stage_no = ls_gate-stage_no.
        ls_stage-status = 'PARTIAL'.
        lv_closed = abap_true.
      ELSE.
        ls_stage-status = ls_gate-status.
        IF ls_stage-status = 'PARTIAL'.
          lv_closed = abap_true.
        ELSEIF ls_stage-status <> 'DONE'.
          lv_final = abap_false.
        ENDIF.
      ENDIF.
      APPEND ls_stage TO rs_result-stages.
    ENDLOOP.
    LOOP AT is_result-rules INTO ls_rule.
      CLEAR: ls_rule-alerts, ls_rule-keys, ls_rule-piles, ls_rule-piles_done, lv_open, lv_lost.
      LOOP AT lt_piles INTO ls_pile WHERE rule_name = ls_rule-rule.
        ls_rule-piles = ls_rule-piles + 1.
        IF ls_pile-status = 'DONE'.
          ls_rule-piles_done = ls_rule-piles_done + 1.
          IF ls_rule-filter = abap_true.
            ls_rule-keys = ls_rule-keys + ls_pile-alerts.
          ELSE.
            ls_rule-alerts = ls_rule-alerts + ls_pile-alerts.
          ENDIF.
        ELSEIF ls_pile-status = 'FAILED'.
          lv_lost = abap_true.
        ELSEIF lv_open IS INITIAL.
          lv_open = ls_pile-status.
        ENDIF.
      ENDLOOP.
      READ TABLE rs_result-stages INTO ls_stage WITH KEY stage_no = ls_rule-stage_no.
      IF ls_stage-status = 'WAITING' OR ls_stage-status = 'NOT-RUN'.
        ls_rule-status = ls_stage-status.
      ELSEIF ls_rule-piles_done = ls_rule-piles.
        ls_rule-status = 'DONE'.
        finalise( iv_rule = ls_rule-rule
                  iv_hash = ls_rule-model_hash
                  iv_date = is_result-check_date
                  iv_run = is_result-run_id
                  iv_bind = is_result-bind ).
      ELSEIF lv_open IS NOT INITIAL.
        ls_rule-status = lv_open.
      ELSE.
        ls_rule-status = 'PARTIAL'.
      ENDIF.
      rs_result-alerts = rs_result-alerts + ls_rule-alerts.
      APPEND ls_rule TO rs_result-rules.
    ENDLOOP.
    IF lv_final = abap_true.
      rs_result-status = 'DONE'.
      LOOP AT rs_result-stages INTO ls_stage WHERE status <> 'DONE'.
        rs_result-status = 'PARTIAL'.
      ENDLOOP.
      release( iv_run = is_result-run_id iv_date = is_result-check_date ).
    ELSE.
      rs_result-status = 'RUNNING'.
    ENDIF.
  ENDMETHOD.
ENDCLASS.
