* Generated by tools/dsl-l3.mjs from src/l3/fleet_watch.l3.yaml; do not edit.
* Port ships of set watch, variant table: the table the rules read.
CLASS zcl_l3_watch_ships_table DEFINITION PUBLIC FINAL CREATE PUBLIC.
  PUBLIC SECTION.
    INTERFACES zif_l3_watch_ships.
ENDCLASS.

CLASS zcl_l3_watch_ships_table IMPLEMENTATION.
  METHOD zif_l3_watch_ships~read.
    SELECT * FROM zosd_fleet_ship INTO TABLE rt_rows WHERE ship_id IN it_range.
  ENDMETHOD.
ENDCLASS.
