* Generated by tools/dsl-l3.mjs from src/l3/fleet_night.l3.yaml; do not edit.
* Port ships of set night, variant worklist: the rows of zosd_fleet_ship whose
* ship_id is in a worklist of one run (ZOSD_L3_WORK), filled by a filter stage.
* The planner of a later stage reads it; a run does not bind it.
CLASS zcl_l3_night_ships_worklist DEFINITION PUBLIC FINAL CREATE PUBLIC.
  PUBLIC SECTION.
    INTERFACES zif_l3_night_ships.
    " the run and the worklist read( ) answers for
    CLASS-METHODS use
      IMPORTING iv_run TYPE csequence
                iv_worklist TYPE csequence.
  PRIVATE SECTION.
    CLASS-DATA gv_run TYPE zosd_l3_work-run_id.
    CLASS-DATA gv_worklist TYPE zosd_l3_work-worklist.
ENDCLASS.

CLASS zcl_l3_night_ships_worklist IMPLEMENTATION.
  METHOD use.
    gv_run = iv_run.
    gv_worklist = iv_worklist.
  ENDMETHOD.

  METHOD zif_l3_night_ships~read.
    " the keys of the run's worklist, then the table's rows for them, IN on
    " the SQL path; an empty worklist is no row (an empty range is every row)
    DATA lt_values TYPE STANDARD TABLE OF zosd_l3_work-key_value WITH DEFAULT KEY.
    DATA lv_value TYPE zosd_l3_work-key_value.
    DATA lt_keys TYPE zif_l3_night_ships=>tt_range.
    DATA ls_key LIKE LINE OF lt_keys.
    SELECT key_value FROM zosd_l3_work INTO TABLE lt_values
      WHERE run_id = gv_run
        AND worklist = gv_worklist.
    IF lt_values IS INITIAL.
      RETURN.
    ENDIF.
    LOOP AT lt_values INTO lv_value.
      ls_key-sign = 'I'.
      ls_key-option = 'EQ'.
      ls_key-low = lv_value.
      APPEND ls_key TO lt_keys.
    ENDLOOP.
    SELECT * FROM zosd_fleet_ship INTO TABLE rt_rows
      WHERE ship_id IN lt_keys
        AND ship_id IN it_range.
  ENDMETHOD.
ENDCLASS.
