* Generated by tools/dsl-l3.mjs from src/l3/fleet_watch.l3.yaml; do not edit.
* Port close of set watch, variant none.
CLASS zcl_l3_watch_close_none DEFINITION PUBLIC FINAL CREATE PUBLIC.
  PUBLIC SECTION.
    INTERFACES zif_l3_watch_close.
ENDCLASS.
CLASS zcl_l3_watch_close_none IMPLEMENTATION.
  METHOD zif_l3_watch_close~apply.
  ENDMETHOD.
ENDCLASS.
