* Generated by tools/dsl-l3.mjs from src/l3/fleet_night.l3.yaml; do not edit.
* Port alerts of set night, variant log: the durable log, zosd_l3_alert.
CLASS zcl_l3_night_alerts_log DEFINITION PUBLIC FINAL CREATE PUBLIC.
  PUBLIC SECTION.
    INTERFACES zif_l3_night_alerts.
ENDCLASS.

CLASS zcl_l3_night_alerts_log IMPLEMENTATION.
  METHOD zif_l3_night_alerts~put.
    " idempotent per group: MODIFY on the key, and the rows of the group past
    " the last row of this run go, so a rerun or a retried job leaves exactly
    " this run's rows in the group; the rows of other groups stay
    DATA ls_row TYPE zosd_l3_alert.
    DATA lv_lines TYPE i.
    lv_lines = lines( it_rows ).
    LOOP AT it_rows INTO ls_row.
      MODIFY zosd_l3_alert FROM ls_row.
      IF sy-subrc = 0.
        rv_count = rv_count + 1.
      ENDIF.
    ENDLOOP.
    DELETE FROM zosd_l3_alert
      WHERE set_name = is_group-set_name
      AND rule_name = is_group-rule_name
      AND model_hash = is_group-model_hash
      AND check_date = is_group-check_date
      AND pile_no = is_group-pile_no
      AND alert_seq > lv_lines.
  ENDMETHOD.
ENDCLASS.
