* Generated by tools/dsl-l2.mjs from src/l3/busy_ship.l2.yaml; do not edit.
* The examples of rule busy-ship and the cases derived from its conditions, one test method each.
* Every method runs check and check_reference (the obvious nested form, one
* SELECT per row) and asserts that they answer alike, then that check answers
* what the rule's interpreter expects.
* RISK LEVEL DANGEROUS: a method inserts its example's rows into the rule's
* own tables and its teardown deletes them again by key.
CLASS ltcl_examples DEFINITION FOR TESTING RISK LEVEL DANGEROUS DURATION SHORT FINAL.
  PRIVATE SECTION.
    TYPES tt_range TYPE RANGE OF zosd_fleet_ship-ship_id.
    DATA mt_zosd_fleet_ship TYPE STANDARD TABLE OF zosd_fleet_ship WITH DEFAULT KEY.
    DATA mt_zosd_fleet_voy TYPE STANDARD TABLE OF zosd_fleet_voy WITH DEFAULT KEY.
    METHODS teardown.
    METHODS check_reference
      IMPORTING iv_date TYPE d
                it_range TYPE tt_range OPTIONAL
      RETURNING VALUE(rt_alerts) TYPE string_table.
    METHODS assert_alerts
      IMPORTING it_act TYPE string_table it_exp TYPE string_table iv_example TYPE string.
    METHODS assert_same_as_reference
      IMPORTING it_act TYPE string_table it_ref TYPE string_table iv_example TYPE string.
    METHODS a_voyage_ahead FOR TESTING.
    METHODS only_past_voyages FOR TESTING.
    METHODS one_key_for_several_voyages FOR TESTING.
    METHODS the_range_keeps_the_inner_ship FOR TESTING.
    METHODS b_ship_id_match FOR TESTING.
    METHODS b_ship_id_nomatch FOR TESTING.
    METHODS b_dep_date_lt FOR TESTING.
    METHODS b_dep_date_eq FOR TESTING.
    METHODS b_dep_date_gt FOR TESTING.
    METHODS b_exists_zero FOR TESTING.
    METHODS b_exists_two FOR TESTING.
ENDCLASS.

CLASS ltcl_examples IMPLEMENTATION.

  METHOD teardown.
    DELETE zosd_fleet_ship FROM TABLE mt_zosd_fleet_ship.
    CLEAR mt_zosd_fleet_ship.
    DELETE zosd_fleet_voy FROM TABLE mt_zosd_fleet_voy.
    CLEAR mt_zosd_fleet_voy.
  ENDMETHOD.

  METHOD check_reference.
    " the rule as a person would write it: a SELECT on the exists table for
    " every row of the first
    DATA lt_ship TYPE STANDARD TABLE OF zosd_fleet_ship WITH DEFAULT KEY.
    DATA ls_ship TYPE zosd_fleet_ship.
    DATA lt_voy TYPE STANDARD TABLE OF zosd_fleet_voy WITH DEFAULT KEY.
    DATA ls_voy TYPE zosd_fleet_voy.
    DATA lv_alert TYPE string.
    SELECT * FROM zosd_fleet_ship INTO TABLE lt_ship
      WHERE ship_id IN it_range
      ORDER BY PRIMARY KEY.
    LOOP AT lt_ship INTO ls_ship.
      SELECT * FROM zosd_fleet_voy INTO TABLE lt_voy
        WHERE ship_id = ls_ship-ship_id
          AND dep_date > iv_date
        ORDER BY PRIMARY KEY.
      LOOP AT lt_voy INTO ls_voy.
        lv_alert = ls_ship-ship_id
          && ` `
          && ls_ship-name
          && `: voyage `
          && ls_voy-voyage_id
          && ` departs `
          && ls_voy-dep_date.
        APPEND lv_alert TO rt_alerts.
      ENDLOOP.
    ENDLOOP.
  ENDMETHOD.

  METHOD assert_alerts.
    " order-insensitive: the rule says which alerts, not in which order
    DATA lt_act TYPE string_table.
    DATA lt_exp TYPE string_table.
    lt_act = it_act.
    lt_exp = it_exp.
    SORT lt_act.
    SORT lt_exp.
    cl_abap_unit_assert=>assert_equals( act = lt_act exp = lt_exp msg = iv_example ).
  ENDMETHOD.

  METHOD assert_same_as_reference.
    " the query and the nested form answer alike, in the same order
    cl_abap_unit_assert=>assert_equals( act = it_act exp = it_ref msg = iv_example ).
  ENDMETHOD.

  METHOD a_voyage_ahead.
    DATA ls_zosd_fleet_ship TYPE zosd_fleet_ship.
    DATA ls_zosd_fleet_voy TYPE zosd_fleet_voy.
    DATA lt_act TYPE string_table.
    DATA lt_ref TYPE string_table.
    DATA lt_exp TYPE string_table.
    DATA lt_keys TYPE zcl_osd_fleet_l3_busy=>tt_range.
    DATA lt_keys_exp TYPE zcl_osd_fleet_l3_busy=>tt_range.
    DATA ls_key LIKE LINE OF lt_keys_exp.
    DATA lt_range TYPE RANGE OF zosd_fleet_ship-ship_id.
    DATA ls_range LIKE LINE OF lt_range.
    CLEAR ls_zosd_fleet_ship.
    ls_zosd_fleet_ship-mandt = sy-mandt.
    ls_zosd_fleet_ship-ship_id = 'X001'.
    ls_zosd_fleet_ship-name = 'Zephyr'.
    ls_zosd_fleet_ship-status = 'A'.
    APPEND ls_zosd_fleet_ship TO mt_zosd_fleet_ship.
    INSERT zosd_fleet_ship FROM TABLE mt_zosd_fleet_ship.
    CLEAR ls_zosd_fleet_voy.
    ls_zosd_fleet_voy-mandt = sy-mandt.
    ls_zosd_fleet_voy-voyage_id = 'X00001'.
    ls_zosd_fleet_voy-ship_id = 'X001'.
    ls_zosd_fleet_voy-dep_date = '20270305'.
    APPEND ls_zosd_fleet_voy TO mt_zosd_fleet_voy.
    INSERT zosd_fleet_voy FROM TABLE mt_zosd_fleet_voy.
    APPEND `X001 Zephyr: voyage X00001 departs 20270305` TO lt_exp.
    lt_act = zcl_osd_fleet_l3_busy=>check( iv_date = '20270301' it_range = lt_range ).
    lt_ref = check_reference( iv_date = '20270301' it_range = lt_range ).
    assert_same_as_reference( it_act = lt_act it_ref = lt_ref iv_example = `a voyage ahead (check against check_reference)` ).
    assert_alerts( it_act = lt_act it_exp = lt_exp iv_example = `a voyage ahead` ).
    " keys( ): the driving keys of the same rows, sorted, each once
    ls_key-sign = 'I'.
    ls_key-option = 'EQ'.
    ls_key-low = 'X001'.
    APPEND ls_key TO lt_keys_exp.
    lt_keys = zcl_osd_fleet_l3_busy=>keys( iv_date = '20270301' it_range = lt_range ).
    cl_abap_unit_assert=>assert_equals( act = lt_keys exp = lt_keys_exp msg = `a voyage ahead (keys)` ).
  ENDMETHOD.

  METHOD only_past_voyages.
    DATA ls_zosd_fleet_ship TYPE zosd_fleet_ship.
    DATA ls_zosd_fleet_voy TYPE zosd_fleet_voy.
    DATA lt_act TYPE string_table.
    DATA lt_ref TYPE string_table.
    DATA lt_exp TYPE string_table.
    DATA lt_keys TYPE zcl_osd_fleet_l3_busy=>tt_range.
    DATA lt_keys_exp TYPE zcl_osd_fleet_l3_busy=>tt_range.
    DATA ls_key LIKE LINE OF lt_keys_exp.
    DATA lt_range TYPE RANGE OF zosd_fleet_ship-ship_id.
    DATA ls_range LIKE LINE OF lt_range.
    CLEAR ls_zosd_fleet_ship.
    ls_zosd_fleet_ship-mandt = sy-mandt.
    ls_zosd_fleet_ship-ship_id = 'X002'.
    ls_zosd_fleet_ship-name = 'Halcyon'.
    ls_zosd_fleet_ship-status = 'D'.
    APPEND ls_zosd_fleet_ship TO mt_zosd_fleet_ship.
    INSERT zosd_fleet_ship FROM TABLE mt_zosd_fleet_ship.
    CLEAR ls_zosd_fleet_voy.
    ls_zosd_fleet_voy-mandt = sy-mandt.
    ls_zosd_fleet_voy-voyage_id = 'X00002'.
    ls_zosd_fleet_voy-ship_id = 'X002'.
    ls_zosd_fleet_voy-dep_date = '20270301'.
    APPEND ls_zosd_fleet_voy TO mt_zosd_fleet_voy.
    INSERT zosd_fleet_voy FROM TABLE mt_zosd_fleet_voy.
    lt_act = zcl_osd_fleet_l3_busy=>check( iv_date = '20270301' it_range = lt_range ).
    lt_ref = check_reference( iv_date = '20270301' it_range = lt_range ).
    assert_same_as_reference( it_act = lt_act it_ref = lt_ref iv_example = `only past voyages (check against check_reference)` ).
    assert_alerts( it_act = lt_act it_exp = lt_exp iv_example = `only past voyages` ).
    " keys( ): the driving keys of the same rows, sorted, each once
    lt_keys = zcl_osd_fleet_l3_busy=>keys( iv_date = '20270301' it_range = lt_range ).
    cl_abap_unit_assert=>assert_equals( act = lt_keys exp = lt_keys_exp msg = `only past voyages (keys)` ).
  ENDMETHOD.

  METHOD one_key_for_several_voyages.
    DATA ls_zosd_fleet_ship TYPE zosd_fleet_ship.
    DATA ls_zosd_fleet_voy TYPE zosd_fleet_voy.
    DATA lt_act TYPE string_table.
    DATA lt_ref TYPE string_table.
    DATA lt_exp TYPE string_table.
    DATA lt_keys TYPE zcl_osd_fleet_l3_busy=>tt_range.
    DATA lt_keys_exp TYPE zcl_osd_fleet_l3_busy=>tt_range.
    DATA ls_key LIKE LINE OF lt_keys_exp.
    DATA lt_range TYPE RANGE OF zosd_fleet_ship-ship_id.
    DATA ls_range LIKE LINE OF lt_range.
    CLEAR ls_zosd_fleet_ship.
    ls_zosd_fleet_ship-mandt = sy-mandt.
    ls_zosd_fleet_ship-ship_id = 'X001'.
    ls_zosd_fleet_ship-name = 'Zephyr'.
    ls_zosd_fleet_ship-status = 'A'.
    APPEND ls_zosd_fleet_ship TO mt_zosd_fleet_ship.
    CLEAR ls_zosd_fleet_ship.
    ls_zosd_fleet_ship-mandt = sy-mandt.
    ls_zosd_fleet_ship-ship_id = 'X003'.
    ls_zosd_fleet_ship-name = 'Skylark'.
    ls_zosd_fleet_ship-status = 'M'.
    APPEND ls_zosd_fleet_ship TO mt_zosd_fleet_ship.
    INSERT zosd_fleet_ship FROM TABLE mt_zosd_fleet_ship.
    CLEAR ls_zosd_fleet_voy.
    ls_zosd_fleet_voy-mandt = sy-mandt.
    ls_zosd_fleet_voy-voyage_id = 'X00003'.
    ls_zosd_fleet_voy-ship_id = 'X003'.
    ls_zosd_fleet_voy-dep_date = '20270310'.
    APPEND ls_zosd_fleet_voy TO mt_zosd_fleet_voy.
    CLEAR ls_zosd_fleet_voy.
    ls_zosd_fleet_voy-mandt = sy-mandt.
    ls_zosd_fleet_voy-voyage_id = 'X00004'.
    ls_zosd_fleet_voy-ship_id = 'X003'.
    ls_zosd_fleet_voy-dep_date = '20270302'.
    APPEND ls_zosd_fleet_voy TO mt_zosd_fleet_voy.
    CLEAR ls_zosd_fleet_voy.
    ls_zosd_fleet_voy-mandt = sy-mandt.
    ls_zosd_fleet_voy-voyage_id = 'X00005'.
    ls_zosd_fleet_voy-ship_id = 'X001'.
    ls_zosd_fleet_voy-dep_date = '20270303'.
    APPEND ls_zosd_fleet_voy TO mt_zosd_fleet_voy.
    INSERT zosd_fleet_voy FROM TABLE mt_zosd_fleet_voy.
    APPEND `X001 Zephyr: voyage X00005 departs 20270303` TO lt_exp.
    APPEND `X003 Skylark: voyage X00003 departs 20270310` TO lt_exp.
    APPEND `X003 Skylark: voyage X00004 departs 20270302` TO lt_exp.
    lt_act = zcl_osd_fleet_l3_busy=>check( iv_date = '20270301' it_range = lt_range ).
    lt_ref = check_reference( iv_date = '20270301' it_range = lt_range ).
    assert_same_as_reference( it_act = lt_act it_ref = lt_ref iv_example = `one key for several voyages (check against check_reference)` ).
    assert_alerts( it_act = lt_act it_exp = lt_exp iv_example = `one key for several voyages` ).
    " keys( ): the driving keys of the same rows, sorted, each once
    ls_key-sign = 'I'.
    ls_key-option = 'EQ'.
    ls_key-low = 'X001'.
    APPEND ls_key TO lt_keys_exp.
    ls_key-sign = 'I'.
    ls_key-option = 'EQ'.
    ls_key-low = 'X003'.
    APPEND ls_key TO lt_keys_exp.
    lt_keys = zcl_osd_fleet_l3_busy=>keys( iv_date = '20270301' it_range = lt_range ).
    cl_abap_unit_assert=>assert_equals( act = lt_keys exp = lt_keys_exp msg = `one key for several voyages (keys)` ).
  ENDMETHOD.

  METHOD the_range_keeps_the_inner_ship.
    DATA ls_zosd_fleet_ship TYPE zosd_fleet_ship.
    DATA ls_zosd_fleet_voy TYPE zosd_fleet_voy.
    DATA lt_act TYPE string_table.
    DATA lt_ref TYPE string_table.
    DATA lt_exp TYPE string_table.
    DATA lt_keys TYPE zcl_osd_fleet_l3_busy=>tt_range.
    DATA lt_keys_exp TYPE zcl_osd_fleet_l3_busy=>tt_range.
    DATA ls_key LIKE LINE OF lt_keys_exp.
    DATA lt_range TYPE RANGE OF zosd_fleet_ship-ship_id.
    DATA ls_range LIKE LINE OF lt_range.
    CLEAR ls_range.
    ls_range-sign = 'I'.
    ls_range-option = 'BT'.
    ls_range-low = 'X002'.
    ls_range-high = 'X003'.
    APPEND ls_range TO lt_range.
    CLEAR ls_zosd_fleet_ship.
    ls_zosd_fleet_ship-mandt = sy-mandt.
    ls_zosd_fleet_ship-ship_id = 'X001'.
    ls_zosd_fleet_ship-name = 'Zephyr'.
    ls_zosd_fleet_ship-status = 'A'.
    APPEND ls_zosd_fleet_ship TO mt_zosd_fleet_ship.
    CLEAR ls_zosd_fleet_ship.
    ls_zosd_fleet_ship-mandt = sy-mandt.
    ls_zosd_fleet_ship-ship_id = 'X003'.
    ls_zosd_fleet_ship-name = 'Skylark'.
    ls_zosd_fleet_ship-status = 'A'.
    APPEND ls_zosd_fleet_ship TO mt_zosd_fleet_ship.
    CLEAR ls_zosd_fleet_ship.
    ls_zosd_fleet_ship-mandt = sy-mandt.
    ls_zosd_fleet_ship-ship_id = 'X004'.
    ls_zosd_fleet_ship-name = 'Kestrel'.
    ls_zosd_fleet_ship-status = 'A'.
    APPEND ls_zosd_fleet_ship TO mt_zosd_fleet_ship.
    INSERT zosd_fleet_ship FROM TABLE mt_zosd_fleet_ship.
    CLEAR ls_zosd_fleet_voy.
    ls_zosd_fleet_voy-mandt = sy-mandt.
    ls_zosd_fleet_voy-voyage_id = 'X00006'.
    ls_zosd_fleet_voy-ship_id = 'X001'.
    ls_zosd_fleet_voy-dep_date = '20270305'.
    APPEND ls_zosd_fleet_voy TO mt_zosd_fleet_voy.
    CLEAR ls_zosd_fleet_voy.
    ls_zosd_fleet_voy-mandt = sy-mandt.
    ls_zosd_fleet_voy-voyage_id = 'X00007'.
    ls_zosd_fleet_voy-ship_id = 'X003'.
    ls_zosd_fleet_voy-dep_date = '20270305'.
    APPEND ls_zosd_fleet_voy TO mt_zosd_fleet_voy.
    CLEAR ls_zosd_fleet_voy.
    ls_zosd_fleet_voy-mandt = sy-mandt.
    ls_zosd_fleet_voy-voyage_id = 'X00008'.
    ls_zosd_fleet_voy-ship_id = 'X004'.
    ls_zosd_fleet_voy-dep_date = '20270305'.
    APPEND ls_zosd_fleet_voy TO mt_zosd_fleet_voy.
    INSERT zosd_fleet_voy FROM TABLE mt_zosd_fleet_voy.
    APPEND `X003 Skylark: voyage X00007 departs 20270305` TO lt_exp.
    lt_act = zcl_osd_fleet_l3_busy=>check( iv_date = '20270301' it_range = lt_range ).
    lt_ref = check_reference( iv_date = '20270301' it_range = lt_range ).
    assert_same_as_reference( it_act = lt_act it_ref = lt_ref iv_example = `the range keeps the inner ship (check against check_reference)` ).
    assert_alerts( it_act = lt_act it_exp = lt_exp iv_example = `the range keeps the inner ship` ).
    " keys( ): the driving keys of the same rows, sorted, each once
    ls_key-sign = 'I'.
    ls_key-option = 'EQ'.
    ls_key-low = 'X003'.
    APPEND ls_key TO lt_keys_exp.
    lt_keys = zcl_osd_fleet_l3_busy=>keys( iv_date = '20270301' it_range = lt_range ).
    cl_abap_unit_assert=>assert_equals( act = lt_keys exp = lt_keys_exp msg = `the range keeps the inner ship (keys)` ).
  ENDMETHOD.

  METHOD b_ship_id_match.
    DATA ls_zosd_fleet_ship TYPE zosd_fleet_ship.
    DATA ls_zosd_fleet_voy TYPE zosd_fleet_voy.
    DATA lt_act TYPE string_table.
    DATA lt_ref TYPE string_table.
    DATA lt_exp TYPE string_table.
    DATA lt_keys TYPE zcl_osd_fleet_l3_busy=>tt_range.
    DATA lt_keys_exp TYPE zcl_osd_fleet_l3_busy=>tt_range.
    DATA ls_key LIKE LINE OF lt_keys_exp.
    DATA lt_range TYPE RANGE OF zosd_fleet_ship-ship_id.
    DATA ls_range LIKE LINE OF lt_range.
    CLEAR ls_zosd_fleet_ship.
    ls_zosd_fleet_ship-mandt = sy-mandt.
    ls_zosd_fleet_ship-ship_id = 'X001'.
    ls_zosd_fleet_ship-name = 'Zephyr'.
    ls_zosd_fleet_ship-status = 'A'.
    ls_zosd_fleet_ship-steam_pct = 1.
    ls_zosd_fleet_ship-home_port = 'A0000000000000000002'.
    APPEND ls_zosd_fleet_ship TO mt_zosd_fleet_ship.
    INSERT zosd_fleet_ship FROM TABLE mt_zosd_fleet_ship.
    CLEAR ls_zosd_fleet_voy.
    ls_zosd_fleet_voy-mandt = sy-mandt.
    ls_zosd_fleet_voy-voyage_id = 'X00001'.
    ls_zosd_fleet_voy-ship_id = 'X001'.
    ls_zosd_fleet_voy-from_port = 'A0000000000000000001'.
    ls_zosd_fleet_voy-to_port = 'A0000000000000000002'.
    ls_zosd_fleet_voy-dep_date = '20270305'.
    ls_zosd_fleet_voy-arr_date = '20260101'.
    ls_zosd_fleet_voy-passengers = 4.
    ls_zosd_fleet_voy-fuel_kg = 5.
    ls_zosd_fleet_voy-distance_km = 6.
    ls_zosd_fleet_voy-dep_month = 'A00007'.
    APPEND ls_zosd_fleet_voy TO mt_zosd_fleet_voy.
    INSERT zosd_fleet_voy FROM TABLE mt_zosd_fleet_voy.
    APPEND `X001 Zephyr: voyage X00001 departs 20270305` TO lt_exp.
    lt_act = zcl_osd_fleet_l3_busy=>check( iv_date = '20270301' it_range = lt_range ).
    lt_ref = check_reference( iv_date = '20270301' it_range = lt_range ).
    assert_same_as_reference( it_act = lt_act it_ref = lt_ref iv_example = `voy.ship_id = ship.ship_id: match (check against check_reference)` ).
    assert_alerts( it_act = lt_act it_exp = lt_exp iv_example = `voy.ship_id = ship.ship_id: match` ).
    " keys( ): the driving keys of the same rows, sorted, each once
    ls_key-sign = 'I'.
    ls_key-option = 'EQ'.
    ls_key-low = 'X001'.
    APPEND ls_key TO lt_keys_exp.
    lt_keys = zcl_osd_fleet_l3_busy=>keys( iv_date = '20270301' it_range = lt_range ).
    cl_abap_unit_assert=>assert_equals( act = lt_keys exp = lt_keys_exp msg = `voy.ship_id = ship.ship_id: match (keys)` ).
  ENDMETHOD.

  METHOD b_ship_id_nomatch.
    DATA ls_zosd_fleet_ship TYPE zosd_fleet_ship.
    DATA ls_zosd_fleet_voy TYPE zosd_fleet_voy.
    DATA lt_act TYPE string_table.
    DATA lt_ref TYPE string_table.
    DATA lt_exp TYPE string_table.
    DATA lt_keys TYPE zcl_osd_fleet_l3_busy=>tt_range.
    DATA lt_keys_exp TYPE zcl_osd_fleet_l3_busy=>tt_range.
    DATA ls_key LIKE LINE OF lt_keys_exp.
    DATA lt_range TYPE RANGE OF zosd_fleet_ship-ship_id.
    DATA ls_range LIKE LINE OF lt_range.
    CLEAR ls_zosd_fleet_ship.
    ls_zosd_fleet_ship-mandt = sy-mandt.
    ls_zosd_fleet_ship-ship_id = 'X001'.
    ls_zosd_fleet_ship-name = 'Zephyr'.
    ls_zosd_fleet_ship-status = 'A'.
    ls_zosd_fleet_ship-steam_pct = 1.
    ls_zosd_fleet_ship-home_port = 'A0000000000000000002'.
    APPEND ls_zosd_fleet_ship TO mt_zosd_fleet_ship.
    INSERT zosd_fleet_ship FROM TABLE mt_zosd_fleet_ship.
    CLEAR ls_zosd_fleet_voy.
    ls_zosd_fleet_voy-mandt = sy-mandt.
    ls_zosd_fleet_voy-voyage_id = 'X00001'.
    ls_zosd_fleet_voy-ship_id = 'X002'.
    ls_zosd_fleet_voy-from_port = 'A0000000000000000001'.
    ls_zosd_fleet_voy-to_port = 'A0000000000000000002'.
    ls_zosd_fleet_voy-dep_date = '20270305'.
    ls_zosd_fleet_voy-arr_date = '20260101'.
    ls_zosd_fleet_voy-passengers = 4.
    ls_zosd_fleet_voy-fuel_kg = 5.
    ls_zosd_fleet_voy-distance_km = 6.
    ls_zosd_fleet_voy-dep_month = 'A00007'.
    APPEND ls_zosd_fleet_voy TO mt_zosd_fleet_voy.
    INSERT zosd_fleet_voy FROM TABLE mt_zosd_fleet_voy.
    lt_act = zcl_osd_fleet_l3_busy=>check( iv_date = '20270301' it_range = lt_range ).
    lt_ref = check_reference( iv_date = '20270301' it_range = lt_range ).
    assert_same_as_reference( it_act = lt_act it_ref = lt_ref iv_example = `voy.ship_id = ship.ship_id: nomatch (check against check_reference)` ).
    assert_alerts( it_act = lt_act it_exp = lt_exp iv_example = `voy.ship_id = ship.ship_id: nomatch` ).
    " keys( ): the driving keys of the same rows, sorted, each once
    lt_keys = zcl_osd_fleet_l3_busy=>keys( iv_date = '20270301' it_range = lt_range ).
    cl_abap_unit_assert=>assert_equals( act = lt_keys exp = lt_keys_exp msg = `voy.ship_id = ship.ship_id: nomatch (keys)` ).
  ENDMETHOD.

  METHOD b_dep_date_lt.
    DATA ls_zosd_fleet_ship TYPE zosd_fleet_ship.
    DATA ls_zosd_fleet_voy TYPE zosd_fleet_voy.
    DATA lt_act TYPE string_table.
    DATA lt_ref TYPE string_table.
    DATA lt_exp TYPE string_table.
    DATA lt_keys TYPE zcl_osd_fleet_l3_busy=>tt_range.
    DATA lt_keys_exp TYPE zcl_osd_fleet_l3_busy=>tt_range.
    DATA ls_key LIKE LINE OF lt_keys_exp.
    DATA lt_range TYPE RANGE OF zosd_fleet_ship-ship_id.
    DATA ls_range LIKE LINE OF lt_range.
    CLEAR ls_zosd_fleet_ship.
    ls_zosd_fleet_ship-mandt = sy-mandt.
    ls_zosd_fleet_ship-ship_id = 'X001'.
    ls_zosd_fleet_ship-name = 'Zephyr'.
    ls_zosd_fleet_ship-status = 'A'.
    ls_zosd_fleet_ship-steam_pct = 1.
    ls_zosd_fleet_ship-home_port = 'A0000000000000000002'.
    APPEND ls_zosd_fleet_ship TO mt_zosd_fleet_ship.
    INSERT zosd_fleet_ship FROM TABLE mt_zosd_fleet_ship.
    CLEAR ls_zosd_fleet_voy.
    ls_zosd_fleet_voy-mandt = sy-mandt.
    ls_zosd_fleet_voy-voyage_id = 'X00001'.
    ls_zosd_fleet_voy-ship_id = 'X001'.
    ls_zosd_fleet_voy-from_port = 'A0000000000000000001'.
    ls_zosd_fleet_voy-to_port = 'A0000000000000000002'.
    ls_zosd_fleet_voy-dep_date = '20270228'.
    ls_zosd_fleet_voy-arr_date = '20260101'.
    ls_zosd_fleet_voy-passengers = 4.
    ls_zosd_fleet_voy-fuel_kg = 5.
    ls_zosd_fleet_voy-distance_km = 6.
    ls_zosd_fleet_voy-dep_month = 'A00007'.
    APPEND ls_zosd_fleet_voy TO mt_zosd_fleet_voy.
    INSERT zosd_fleet_voy FROM TABLE mt_zosd_fleet_voy.
    lt_act = zcl_osd_fleet_l3_busy=>check( iv_date = '20270301' it_range = lt_range ).
    lt_ref = check_reference( iv_date = '20270301' it_range = lt_range ).
    assert_same_as_reference( it_act = lt_act it_ref = lt_ref iv_example = `voy.dep_date > $date: lt (check against check_reference)` ).
    assert_alerts( it_act = lt_act it_exp = lt_exp iv_example = `voy.dep_date > $date: lt` ).
    " keys( ): the driving keys of the same rows, sorted, each once
    lt_keys = zcl_osd_fleet_l3_busy=>keys( iv_date = '20270301' it_range = lt_range ).
    cl_abap_unit_assert=>assert_equals( act = lt_keys exp = lt_keys_exp msg = `voy.dep_date > $date: lt (keys)` ).
  ENDMETHOD.

  METHOD b_dep_date_eq.
    DATA ls_zosd_fleet_ship TYPE zosd_fleet_ship.
    DATA ls_zosd_fleet_voy TYPE zosd_fleet_voy.
    DATA lt_act TYPE string_table.
    DATA lt_ref TYPE string_table.
    DATA lt_exp TYPE string_table.
    DATA lt_keys TYPE zcl_osd_fleet_l3_busy=>tt_range.
    DATA lt_keys_exp TYPE zcl_osd_fleet_l3_busy=>tt_range.
    DATA ls_key LIKE LINE OF lt_keys_exp.
    DATA lt_range TYPE RANGE OF zosd_fleet_ship-ship_id.
    DATA ls_range LIKE LINE OF lt_range.
    CLEAR ls_zosd_fleet_ship.
    ls_zosd_fleet_ship-mandt = sy-mandt.
    ls_zosd_fleet_ship-ship_id = 'X001'.
    ls_zosd_fleet_ship-name = 'Zephyr'.
    ls_zosd_fleet_ship-status = 'A'.
    ls_zosd_fleet_ship-steam_pct = 1.
    ls_zosd_fleet_ship-home_port = 'A0000000000000000002'.
    APPEND ls_zosd_fleet_ship TO mt_zosd_fleet_ship.
    INSERT zosd_fleet_ship FROM TABLE mt_zosd_fleet_ship.
    CLEAR ls_zosd_fleet_voy.
    ls_zosd_fleet_voy-mandt = sy-mandt.
    ls_zosd_fleet_voy-voyage_id = 'X00001'.
    ls_zosd_fleet_voy-ship_id = 'X001'.
    ls_zosd_fleet_voy-from_port = 'A0000000000000000001'.
    ls_zosd_fleet_voy-to_port = 'A0000000000000000002'.
    ls_zosd_fleet_voy-dep_date = '20270301'.
    ls_zosd_fleet_voy-arr_date = '20260101'.
    ls_zosd_fleet_voy-passengers = 4.
    ls_zosd_fleet_voy-fuel_kg = 5.
    ls_zosd_fleet_voy-distance_km = 6.
    ls_zosd_fleet_voy-dep_month = 'A00007'.
    APPEND ls_zosd_fleet_voy TO mt_zosd_fleet_voy.
    INSERT zosd_fleet_voy FROM TABLE mt_zosd_fleet_voy.
    lt_act = zcl_osd_fleet_l3_busy=>check( iv_date = '20270301' it_range = lt_range ).
    lt_ref = check_reference( iv_date = '20270301' it_range = lt_range ).
    assert_same_as_reference( it_act = lt_act it_ref = lt_ref iv_example = `voy.dep_date > $date: eq (check against check_reference)` ).
    assert_alerts( it_act = lt_act it_exp = lt_exp iv_example = `voy.dep_date > $date: eq` ).
    " keys( ): the driving keys of the same rows, sorted, each once
    lt_keys = zcl_osd_fleet_l3_busy=>keys( iv_date = '20270301' it_range = lt_range ).
    cl_abap_unit_assert=>assert_equals( act = lt_keys exp = lt_keys_exp msg = `voy.dep_date > $date: eq (keys)` ).
  ENDMETHOD.

  METHOD b_dep_date_gt.
    DATA ls_zosd_fleet_ship TYPE zosd_fleet_ship.
    DATA ls_zosd_fleet_voy TYPE zosd_fleet_voy.
    DATA lt_act TYPE string_table.
    DATA lt_ref TYPE string_table.
    DATA lt_exp TYPE string_table.
    DATA lt_keys TYPE zcl_osd_fleet_l3_busy=>tt_range.
    DATA lt_keys_exp TYPE zcl_osd_fleet_l3_busy=>tt_range.
    DATA ls_key LIKE LINE OF lt_keys_exp.
    DATA lt_range TYPE RANGE OF zosd_fleet_ship-ship_id.
    DATA ls_range LIKE LINE OF lt_range.
    CLEAR ls_zosd_fleet_ship.
    ls_zosd_fleet_ship-mandt = sy-mandt.
    ls_zosd_fleet_ship-ship_id = 'X001'.
    ls_zosd_fleet_ship-name = 'Zephyr'.
    ls_zosd_fleet_ship-status = 'A'.
    ls_zosd_fleet_ship-steam_pct = 1.
    ls_zosd_fleet_ship-home_port = 'A0000000000000000002'.
    APPEND ls_zosd_fleet_ship TO mt_zosd_fleet_ship.
    INSERT zosd_fleet_ship FROM TABLE mt_zosd_fleet_ship.
    CLEAR ls_zosd_fleet_voy.
    ls_zosd_fleet_voy-mandt = sy-mandt.
    ls_zosd_fleet_voy-voyage_id = 'X00001'.
    ls_zosd_fleet_voy-ship_id = 'X001'.
    ls_zosd_fleet_voy-from_port = 'A0000000000000000001'.
    ls_zosd_fleet_voy-to_port = 'A0000000000000000002'.
    ls_zosd_fleet_voy-dep_date = '20270302'.
    ls_zosd_fleet_voy-arr_date = '20260101'.
    ls_zosd_fleet_voy-passengers = 4.
    ls_zosd_fleet_voy-fuel_kg = 5.
    ls_zosd_fleet_voy-distance_km = 6.
    ls_zosd_fleet_voy-dep_month = 'A00007'.
    APPEND ls_zosd_fleet_voy TO mt_zosd_fleet_voy.
    INSERT zosd_fleet_voy FROM TABLE mt_zosd_fleet_voy.
    APPEND `X001 Zephyr: voyage X00001 departs 20270302` TO lt_exp.
    lt_act = zcl_osd_fleet_l3_busy=>check( iv_date = '20270301' it_range = lt_range ).
    lt_ref = check_reference( iv_date = '20270301' it_range = lt_range ).
    assert_same_as_reference( it_act = lt_act it_ref = lt_ref iv_example = `voy.dep_date > $date: gt (check against check_reference)` ).
    assert_alerts( it_act = lt_act it_exp = lt_exp iv_example = `voy.dep_date > $date: gt` ).
    " keys( ): the driving keys of the same rows, sorted, each once
    ls_key-sign = 'I'.
    ls_key-option = 'EQ'.
    ls_key-low = 'X001'.
    APPEND ls_key TO lt_keys_exp.
    lt_keys = zcl_osd_fleet_l3_busy=>keys( iv_date = '20270301' it_range = lt_range ).
    cl_abap_unit_assert=>assert_equals( act = lt_keys exp = lt_keys_exp msg = `voy.dep_date > $date: gt (keys)` ).
  ENDMETHOD.

  METHOD b_exists_zero.
    DATA ls_zosd_fleet_ship TYPE zosd_fleet_ship.
    DATA lt_act TYPE string_table.
    DATA lt_ref TYPE string_table.
    DATA lt_exp TYPE string_table.
    DATA lt_keys TYPE zcl_osd_fleet_l3_busy=>tt_range.
    DATA lt_keys_exp TYPE zcl_osd_fleet_l3_busy=>tt_range.
    DATA ls_key LIKE LINE OF lt_keys_exp.
    DATA lt_range TYPE RANGE OF zosd_fleet_ship-ship_id.
    DATA ls_range LIKE LINE OF lt_range.
    CLEAR ls_zosd_fleet_ship.
    ls_zosd_fleet_ship-mandt = sy-mandt.
    ls_zosd_fleet_ship-ship_id = 'X001'.
    ls_zosd_fleet_ship-name = 'Zephyr'.
    ls_zosd_fleet_ship-status = 'A'.
    ls_zosd_fleet_ship-steam_pct = 1.
    ls_zosd_fleet_ship-home_port = 'A0000000000000000002'.
    APPEND ls_zosd_fleet_ship TO mt_zosd_fleet_ship.
    INSERT zosd_fleet_ship FROM TABLE mt_zosd_fleet_ship.
    lt_act = zcl_osd_fleet_l3_busy=>check( iv_date = '20270301' it_range = lt_range ).
    lt_ref = check_reference( iv_date = '20270301' it_range = lt_range ).
    assert_same_as_reference( it_act = lt_act it_ref = lt_ref iv_example = `exists ZOSD_FLEET_VOY as voy: zero (check against check_reference)` ).
    assert_alerts( it_act = lt_act it_exp = lt_exp iv_example = `exists ZOSD_FLEET_VOY as voy: zero` ).
    " keys( ): the driving keys of the same rows, sorted, each once
    lt_keys = zcl_osd_fleet_l3_busy=>keys( iv_date = '20270301' it_range = lt_range ).
    cl_abap_unit_assert=>assert_equals( act = lt_keys exp = lt_keys_exp msg = `exists ZOSD_FLEET_VOY as voy: zero (keys)` ).
  ENDMETHOD.

  METHOD b_exists_two.
    DATA ls_zosd_fleet_ship TYPE zosd_fleet_ship.
    DATA ls_zosd_fleet_voy TYPE zosd_fleet_voy.
    DATA lt_act TYPE string_table.
    DATA lt_ref TYPE string_table.
    DATA lt_exp TYPE string_table.
    DATA lt_keys TYPE zcl_osd_fleet_l3_busy=>tt_range.
    DATA lt_keys_exp TYPE zcl_osd_fleet_l3_busy=>tt_range.
    DATA ls_key LIKE LINE OF lt_keys_exp.
    DATA lt_range TYPE RANGE OF zosd_fleet_ship-ship_id.
    DATA ls_range LIKE LINE OF lt_range.
    CLEAR ls_zosd_fleet_ship.
    ls_zosd_fleet_ship-mandt = sy-mandt.
    ls_zosd_fleet_ship-ship_id = 'X001'.
    ls_zosd_fleet_ship-name = 'Zephyr'.
    ls_zosd_fleet_ship-status = 'A'.
    ls_zosd_fleet_ship-steam_pct = 1.
    ls_zosd_fleet_ship-home_port = 'A0000000000000000002'.
    APPEND ls_zosd_fleet_ship TO mt_zosd_fleet_ship.
    INSERT zosd_fleet_ship FROM TABLE mt_zosd_fleet_ship.
    CLEAR ls_zosd_fleet_voy.
    ls_zosd_fleet_voy-mandt = sy-mandt.
    ls_zosd_fleet_voy-voyage_id = 'X00001'.
    ls_zosd_fleet_voy-ship_id = 'X001'.
    ls_zosd_fleet_voy-from_port = 'A0000000000000000001'.
    ls_zosd_fleet_voy-to_port = 'A0000000000000000002'.
    ls_zosd_fleet_voy-dep_date = '20270305'.
    ls_zosd_fleet_voy-arr_date = '20260101'.
    ls_zosd_fleet_voy-passengers = 4.
    ls_zosd_fleet_voy-fuel_kg = 5.
    ls_zosd_fleet_voy-distance_km = 6.
    ls_zosd_fleet_voy-dep_month = 'A00007'.
    APPEND ls_zosd_fleet_voy TO mt_zosd_fleet_voy.
    CLEAR ls_zosd_fleet_voy.
    ls_zosd_fleet_voy-mandt = sy-mandt.
    ls_zosd_fleet_voy-voyage_id = 'X00002'.
    ls_zosd_fleet_voy-ship_id = 'X001'.
    ls_zosd_fleet_voy-from_port = 'A0000000000000000001'.
    ls_zosd_fleet_voy-to_port = 'A0000000000000000002'.
    ls_zosd_fleet_voy-dep_date = '20270305'.
    ls_zosd_fleet_voy-arr_date = '20260101'.
    ls_zosd_fleet_voy-passengers = 4.
    ls_zosd_fleet_voy-fuel_kg = 5.
    ls_zosd_fleet_voy-distance_km = 6.
    ls_zosd_fleet_voy-dep_month = 'A00007'.
    APPEND ls_zosd_fleet_voy TO mt_zosd_fleet_voy.
    INSERT zosd_fleet_voy FROM TABLE mt_zosd_fleet_voy.
    APPEND `X001 Zephyr: voyage X00001 departs 20270305` TO lt_exp.
    APPEND `X001 Zephyr: voyage X00002 departs 20270305` TO lt_exp.
    lt_act = zcl_osd_fleet_l3_busy=>check( iv_date = '20270301' it_range = lt_range ).
    lt_ref = check_reference( iv_date = '20270301' it_range = lt_range ).
    assert_same_as_reference( it_act = lt_act it_ref = lt_ref iv_example = `exists ZOSD_FLEET_VOY as voy: two (check against check_reference)` ).
    assert_alerts( it_act = lt_act it_exp = lt_exp iv_example = `exists ZOSD_FLEET_VOY as voy: two` ).
    " keys( ): the driving keys of the same rows, sorted, each once
    ls_key-sign = 'I'.
    ls_key-option = 'EQ'.
    ls_key-low = 'X001'.
    APPEND ls_key TO lt_keys_exp.
    lt_keys = zcl_osd_fleet_l3_busy=>keys( iv_date = '20270301' it_range = lt_range ).
    cl_abap_unit_assert=>assert_equals( act = lt_keys exp = lt_keys_exp msg = `exists ZOSD_FLEET_VOY as voy: two (keys)` ).
  ENDMETHOD.
ENDCLASS.
