* Generated by tools/dsl-l3.mjs from src/l3/fleet_watch.l3.yaml; do not edit.
* Port ships of set watch: a source of zosd_fleet_ship rows.
INTERFACE zif_l3_watch_ships PUBLIC.
  TYPES tt_rows TYPE STANDARD TABLE OF zosd_fleet_ship WITH DEFAULT KEY.
  TYPES tt_range TYPE RANGE OF zosd_fleet_ship-ship_id.
  " the rows for a key range; an empty range is every row
  METHODS read
    IMPORTING it_range TYPE tt_range OPTIONAL
    RETURNING VALUE(rt_rows) TYPE tt_rows.
ENDINTERFACE.
