* Generated by tools/dsl-l3.mjs from src/l3/fleet_watch.l3.yaml; do not edit.
* Port alerts of set watch: a sink of zosd_l3_alert rows.
INTERFACE zif_l3_watch_alerts PUBLIC.
  TYPES tt_rows TYPE STANDARD TABLE OF zosd_l3_alert WITH DEFAULT KEY.
  TYPES: BEGIN OF ty_group,
           set_name TYPE zosd_l3_alert-set_name,
           rule_name TYPE zosd_l3_alert-rule_name,
           model_hash TYPE zosd_l3_alert-model_hash,
           check_date TYPE zosd_l3_alert-check_date,
           pile_no TYPE zosd_l3_alert-pile_no,
         END OF ty_group.
  " the rows of one group (its key fields given in is_group) as the run found
  " them, in alert_seq order; the answer is how many rows the sink took
  METHODS put
    IMPORTING it_rows TYPE tt_rows
              is_group TYPE ty_group
    RETURNING VALUE(rv_count) TYPE i.
ENDINTERFACE.
