* Generated by tools/dsl-l3.mjs from src/l3/fleet_watch.l3.yaml; do not edit.
* Port close of set watch: automatic closure of alert rows.
INTERFACE zif_l3_watch_close PUBLIC.
  TYPES tt_rows TYPE STANDARD TABLE OF zosd_l3_alert WITH DEFAULT KEY.
  " return a subset of it_alerts; closing the durable log is the variant's job
  METHODS apply IMPORTING it_alerts TYPE tt_rows RETURNING VALUE(rt_closed) TYPE tt_rows.
ENDINTERFACE.
