REPORT zl3_watch_conf.
* Generated by tools/dsl-l3.mjs from src/l3/fleet_watch.l3.yaml; do not edit.
PARAMETERS p_param TYPE c LENGTH 30 LOWER CASE.
PARAMETERS p_value TYPE c LENGTH 40 LOWER CASE.
PARAMETERS p_note TYPE c LENGTH 80 LOWER CASE.
PARAMETERS p_reset AS CHECKBOX.
START-OF-SELECTION.
  DATA lt_rows TYPE zcl_l3_watch_conf=>tt_conf.
  DATA ls_row TYPE zosd_l3_conf.
  DATA lv_ok TYPE abap_bool.
  IF p_param IS NOT INITIAL.
    IF p_reset = abap_true.
      lv_ok = zcl_osd_fleet_watch=>reset_setting( p_param ).
    ELSE.
      lv_ok = zcl_osd_fleet_watch=>set_setting( iv_param = p_param iv_value = p_value iv_note = p_note ).
    ENDIF.
    IF lv_ok = abap_false.
      MESSAGE 'Unknown setting or value outside its bounds' TYPE 'E'.
    ENDIF.
  ENDIF.
  zcl_osd_fleet_watch=>settings_seed( ).
  SELECT * FROM zosd_l3_conf INTO TABLE lt_rows WHERE set_name = 'watch'.
  LOOP AT lt_rows INTO ls_row.
    WRITE: / ls_row-param_name, ls_row-param_val, ls_row-origin,
      ls_row-dsl_value, ls_row-changed_by, ls_row-changed_at.
    IF ls_row-param_val <> ls_row-dsl_value.
      WRITE 'DRIFT'.
    ENDIF.
  ENDLOOP.
