REPORT zosd_fleet_night.
* Generated by tools/dsl-l3.mjs from src/l3/fleet_night.l3.yaml; do not edit.
* Set night: one rule of the set as one background job step,
* submitted by zcl_osd_fleet_night=>run( iv_mode = 'P' ).
* One pile of the rule: the job reads its range from the plan row
* ZOSD_L3_PILE (set, p_run, p_rule, p_pile), not from a selection field.
* A pile that ends DONE commits, then asks the gate: the job that finds
* every pile of its stage DONE opens the next stage (advance).
* p_mode = 'D' is the driver of the schedule: one run of the set in jobs
* for the current date; 'R' (the default) runs one rule's pile.

PARAMETERS p_rule TYPE c LENGTH 60 LOWER CASE.
PARAMETERS p_date TYPE d.
PARAMETERS p_run TYPE c LENGTH 32.
PARAMETERS p_pile TYPE i.
PARAMETERS p_bind TYPE c LENGTH 255 LOWER CASE.
PARAMETERS p_mode TYPE c LENGTH 1 DEFAULT 'R'.

START-OF-SELECTION.
  DATA ls_rule TYPE zcl_osd_fleet_night=>ty_rule.
  DATA lv_bind TYPE string.
  DATA ls_result TYPE zcl_osd_fleet_night=>ty_result.
  DATA ls_deleted TYPE zcl_osd_fleet_night=>ty_unschedule.
  IF p_mode = 'U'.
    ls_deleted = zcl_osd_fleet_night=>unschedule( ).
    WRITE: / 'deleted', ls_deleted-deleted, 'refused', ls_deleted-refused.
    RETURN.
  ENDIF.
  IF p_mode = 'D'.
    " the date of the moment the instance starts, not of when it was planned
    GET TIME.
    ls_result = zcl_osd_fleet_night=>run( iv_date = sy-datum iv_mode = zcl_osd_fleet_night=>c_parallel ).
    WRITE: / ls_result-run_id, ls_result-status.
    RETURN.
  ENDIF.
  lv_bind = p_bind.
  ls_rule = zcl_osd_fleet_night=>run_rule(
    iv_rule = p_rule
    iv_date = p_date
    iv_run = p_run
    iv_pile = p_pile
    iv_bind = lv_bind ).
  WRITE: / ls_rule-rule, ls_rule-status, ls_rule-alerts.
  IF ls_rule-status = 'DONE'.
    " the pile's DONE is committed first, so the gate sees it
    COMMIT WORK.
    zcl_osd_fleet_night=>advance( iv_run = p_run
      iv_date = p_date
      iv_stage = ls_rule-stage_no
      iv_bind = lv_bind ).
  ENDIF.
  IF ls_rule-status <> 'DONE'.
    MESSAGE 'The rule did not run to the end; see the list' TYPE 'E'.
  ENDIF.
