REPORT zosd_fleet_watch.
* Generated by tools/dsl-l3.mjs from src/l3/fleet_watch.l3.yaml; do not edit.
* Set watch: one rule of the set as one background job step,
* submitted by zcl_osd_fleet_watch=>run( iv_mode = 'P' ).
* One pile of the rule: the job reads its range from the plan row
* ZOSD_L3_PILE (set, p_run, p_rule, p_pile), not from a selection field.
* A pile that ends DONE commits, then asks the gate: the job that finds
* every pile of its stage DONE opens the next stage (advance).
* A pile the kill switch sent back, or one past the fuse, commits its row
* and ends the job without aborting it.

PARAMETERS p_rule TYPE c LENGTH 60 LOWER CASE.
PARAMETERS p_date TYPE d.
PARAMETERS p_run TYPE c LENGTH 32.
PARAMETERS p_pile TYPE i.
PARAMETERS p_bind TYPE c LENGTH 255 LOWER CASE.
PARAMETERS s_1 TYPE c LENGTH 40 LOWER CASE.

START-OF-SELECTION.
  DATA ls_rule TYPE zcl_osd_fleet_watch=>ty_rule.
  DATA lv_bind TYPE string.
  DATA ls_settings TYPE zcl_l3_watch_conf=>ty_values.
  ls_settings-budget_glass = s_1.
  lv_bind = p_bind.
  ls_rule = zcl_osd_fleet_watch=>run_rule(
    iv_rule = p_rule
    iv_date = p_date
    iv_run = p_run
    is_settings = ls_settings
    iv_pile = p_pile
    iv_bind = lv_bind ).
  WRITE: / ls_rule-rule, ls_rule-status, ls_rule-alerts.
  COMMIT WORK.
  IF ls_rule-status = 'DONE'.
    zcl_osd_fleet_watch=>advance( iv_run = p_run iv_date = p_date iv_stage = ls_rule-stage_no
      iv_bind = lv_bind ).
  ENDIF.
  zcl_osd_fleet_watch=>pile_done( iv_run = p_run iv_pile = p_pile ).
